### ISSUE TITLE
optware-ng possible?

### ISSUE THREAD

**Issue by spiltmilk1111** [jotyGill/openpyn-nordvpn#104]
Curious as if able to use with optware ng as opposed to entware?

is this a thing maybe?

**Comment by jotyGill** [comment]
No clue, you would have to ask [1951FDG](https://github.com/1951FDG/openpyn-nordvpn)

**Comment by 1951FDG** [comment]
@spiltmilk1111 it has been tested on a ASUS router only, what router are you using?

**Comment by spiltmilk1111** [comment]
Using an asus RTN66U optware-ng

**Comment by 1951FDG** [comment]
Are you running standard stock firmware or ASUSWRT-Merlin?

Could you open a ssh session to get the output of `/bin/uname -o`, and post it here

Thanks

**Comment by spiltmilk1111** [comment]
ASUSWRT-Merlin RT-N66U 380.69-2 Sun Jan 28 06:07:49 UTC 2018
admin@RT-N66R-16B0:/tmp/home/root# /bin/uname -o
ASUSWRT-Merlin
admin@RT-N66R-16B0:/tmp/home/root# 

----- Original Message -----

**Comment by spiltmilk1111** [comment]
ASUSWRT-Merlin RT-N66U 380.69-2 Sun Jan 28 06:07:49 UTC 2018
admin@RT-N66R-16B0:/tmp/home/root# /bin/uname -o
ASUSWRT-Merlin
admin@RT-N66R-16B0:/tmp/home/root# 

i was planing on installing (mipsel,std) -
http://entware-3x.zyxmon.org/binaries/mipsel/installer/install_std.sh
[1]

	I have checked the package list and all dependecies are met.

	opkg install git-http iputils-ping procps-ng-pgrep python3-pip sudo
unzip wget

 cd /opt/tmp
 git clone https://github.com/1951FDG/openpyn-nordvpn.git
 cd openpyn-nordvpn/
 git checkout RT-AC86U-E5F0
 git pull
 pip3 install -U setuptools
 pip3 install --upgrade .

 echo "" >>/etc/passwd
 echo "root:x:0:0:root:/root:/bin/sh" >>/etc/passwd

 ###Add your router username to sudoers list, change only if is
different than "admin"
 echo "" >>/opt/etc/sudoers
 echo "admin ALL=(ALL) ALL" >>/opt/etc/sudoers

###Start setup and enter your nordvpn credentials
 sudo openpyn --init

 /opt/etc/init.d/S23openpyn start

DO I NEED TO SUBSTITUTE THIS LINE?   GIT CHECKOUT RT-AC86U-E5F0

----- Original Message -----

**Comment by 1951FDG** [comment]
oops actually due to recent changes, i'm going to update the README file.  You don't need to do GIT CHECKOUT RT-AC86U-E5F0, and you could opt to clone this master repository instead of my fork.

Regarding optware-ng, it should work, both the script itself and the nvram option, give it a try,

**Comment by 1951FDG** [comment]
Hey do something like `ipkg list | grep git` to filter all lines containing git and find the appropiate package name, or maybe you don't need it altogether if this works `git clone git@github.com:jotyGill/openpyn-nordvpn.git`

**Comment by spiltmilk1111** [comment]
i get....

admin@RT-N66R-16B0:/tmp/share# git clone
https://github.com/jotyGill/openpyn-nordvpn.git
Cloning into 'openpyn-nordvpn'..
remote: Counting objects: 1249, done.
remote: Compressing objects: 100% (94/94), done.
remote: Total 1249 (delta 88), reused 87 (delta 45), pack-reused 1109
Receiving objects: 100% (1249/1249), 276.54 KiB | 184.00 KiB/s, done.
Resolving deltas: 100% (775/775), done.
Checking connectivity... done.
admin@RT-N66R-16B0:/tmp/share# cd openpyn-nordvpn/
admin@RT-N66R-16B0:/tmp/share/openpyn-nordvpn# git pull
Already up-to-date.
admin@RT-N66R-16B0:/tmp/share/openpyn-nordvpn# pip3 install --upgrade
setuptools
Traceback (most recent call last):
  File "/opt/bin/pip3", line 5, in 
    from pkg_resources import load_entry_point
  File
"/opt/local/lib/python3.5/site-packages/pkg_resources/__init__.py",
line 36, in 
    import email.parser
  File "/opt/lib/python3.5/email/parser.py", line 12, in 
    from email.feedparser import FeedParser, BytesFeedParser
  File "/opt/lib/python3.5/email/feedparser.py", line 27, in 
    from email import message
  File "/opt/lib/python3.5/email/message.py", line 16, in 
    from email import utils
  File "/opt/lib/python3.5/email/utils.py", line 29, in 
    import socket
  File "/opt/lib/python3.5/socket.py", line 49, in 
    import _socket
ImportError: No module named '_socket'
admin@RT-N66R-16B0:/tmp/share/openpyn-nordvpn# pip3 install --upgrade
.

----- Original Message -----

**Comment by 1951FDG** [comment]
maybe skip this line, pip3 install --upgrade setuptools, maybe it's not required on your setup

**Comment by spiltmilk1111** [comment]
ok so i tried 

	cd /tmp/share/ git clone
https://github.com/jotyGill/openpyn-nordvpn.git cd openpyn-nordvpn/
git pull

and everything seems ok

	sudo openpyn --init

then i get..

	admin@RT-N66R-16B0:/tmp/share/openpyn-nordvpn# sudo openpyn --init
sudo: unknown user: root
sudo: unable to initialize policy plugin
admin@RT-N66R-16B0:/tmp/share/openpyn-nordvpn# 

after installing sudo is there something else i need to do?

----- Original Message -----

**Comment by 1951FDG** [comment]
Ok, sorry for getting back late, was tired...

I had this same issue when not using entware 3x, basically if you run `awk -F':' '{ print $1}' /etc/passwd` _**root**_ won't show up, what you want to is:

1. `vi /etc/passwd` to see contents and edits contents of file
2. add `root:x:0:0:root:/root:/bin/sh` to the beginning of the file as the first line, all other lines should be left and should follow this line
3. test again `sudo openpyn --init`

Basically when you run a ssh session to the router, you are running as root, actually the sudo commands in the script itself and the sudo before `openpyn --init` is not even required since you are root already, the problem lies that root is not in the /etc/passwd file, entware 3x reads another passwd where root is defined for example and that passwd takes precedence, which is a nice added benefit of entware 3x.

And:

Another issue is that when your reboot, which I believe in your case will also be the case, /etc/passwd will reset to its default values. I believe this is probably mounted as a RAM drive on boot, hence why it is editable but doesn't save on reboots,....

So if you reboot, you may need to edit the /etc/passwd file every time.

Other solution would be to not use sudo when invoking openpyn and removing all instances of sudo in the python files before installing/upgrading openpyn

Or:

The python files have to be rewritten in such a way that the user for sudo can be specified by an argument passed to openpyn, to run sudo -u admin, which would in turn run sudo as admin user, which is present in /etc/passwd by default, I don't know however if @jotyGill wants to implement that functionality to be able to specify which user will invoke the sudo commands, as there are sudo commands everywhere....

**Comment by spiltmilk1111** [comment]
reply thank you so much for your time 

after editing the  /etc/passwd

it now returns...

root@RT-N66R-16B0:/tmp/share# cd /tmp/share/
root@RT-N66R-16B0:/tmp/share# git clone
https://github.com/jotyGill/openpyn-nord
vpn.git
Cloning into 'openpyn-nordvpn'...
remote: Counting objects: 1249, done.
remote: Compressing objects: 100% (94/94), done.
remote: Total 1249 (delta 88), reused 87 (delta 45), pack-reused 1109
Receiving objects: 100% (1249/1249), 276.54 KiB | 256.00 KiB/s, done.
Resolving deltas: 100% (775/775), done.
Checking connectivity... done.
root@RT-N66R-16B0:/tmp/share# cd openpyn-nordvpn/
root@RT-N66R-16B0:/tmp/share/openpyn-nordvpn# git pull
Already up-to-date.
root@RT-N66R-16B0:/tmp/share/openpyn-nordvpn# sudo openpyn --init
sudo: openpyn: command not found
root@RT-N66R-16B0:/tmp/share/openpyn-nordvpn# ls
LICENSE.md   MANIFEST.in  README.md    openpyn     
setup.cfg    setup.py
root@RT-N66R-16B0:/tmp/share/openpyn-nordvpn# 

----- Original Message -----

**Comment by 1951FDG** [comment]
While in that directory, you have to install this package first, you've basically skipped the most important step, pip3 install --upgrade .

**Comment by 1951FDG** [comment]
After you have installed openpyn, only then can you invoke it

**Comment by spiltmilk1111** [comment]
ok i think i have done what you said but this is what it returns..

root@RT-N66R-16B0:/tmp/share# git clone
https://github.com/jotyGill/openpyn-nord
vpn.git
Cloning into 'openpyn-nordvpn'...
remote: Counting objects: 1249, done.
remote: Compressing objects: 100% (94/94), done.
remote: Total 1249 (delta 88), reused 87 (delta 45), pack-reused 1109
Receiving objects: 100% (1249/1249), 276.54 KiB | 225.00 KiB/s, done.
Resolving deltas: 100% (775/775), done.
Checking connectivity... done.
root@RT-N66R-16B0:/tmp/share# cd openpyn-nordvpn/
root@RT-N66R-16B0:/tmp/share/openpyn-nordvpn# git pull
Already up-to-date.
root@RT-N66R-16B0:/tmp/share/openpyn-nordvpn# pip3 install --upgrade .
Traceback (most recent call last):
  File "/opt/bin/pip3", line 5, in 
    from pkg_resources import load_entry_point
  File
"/opt/local/lib/python3.5/site-packages/pkg_resources/__init__.py",
line 36, in 
    import email.parser
  File "/opt/lib/python3.5/email/parser.py", line 12, in 
    from email.feedparser import FeedParser, BytesFeedParser
  File "/opt/lib/python3.5/email/feedparser.py", line 27, in 
    from email import message
  File "/opt/lib/python3.5/email/message.py", line 16, in 
    from email import utils
  File "/opt/lib/python3.5/email/utils.py", line 29, in 
    import socket
  File "/opt/lib/python3.5/socket.py", line 49, in 
    import _socket
ImportError: No module named '_socket'

what do you think?

kind regards

Adrian Ellies

----- Original Message -----

**Comment by jotyGill** [comment]
How about installing it using 
`python3 setup.py install`

**Comment by spiltmilk1111** [comment]
this is what i get

root@RT-N66R-16B0:/tmp/share/openpyn-nordvpn# python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 6, in 
    import setuptools
  File
"/opt/local/lib/python3.5/site-packages/setuptools/__init__.py", line
10, in 
    from setuptools.extern.six.moves import filter, filterfalse,
map
  File
"/opt/local/lib/python3.5/site-packages/setuptools/extern/__init__.py",
line 1, in 
    from pkg_resources.extern import VendorImporter
  File
"/opt/local/lib/python3.5/site-packages/pkg_resources/__init__.py",
line 36, in 
    import email.parser
  File "/opt/lib/python3.5/email/parser.py", line 12, in 
    from email.feedparser import FeedParser, BytesFeedParser
  File "/opt/lib/python3.5/email/feedparser.py", line 27, in 
    from email import message
  File "/opt/lib/python3.5/email/message.py", line 16, in 
    from email import utils
  File "/opt/lib/python3.5/email/utils.py", line 29, in 
    import socket
  File "/opt/lib/python3.5/socket.py", line 49, in 
    import _socket
ImportError: No module named '_socket'
root@RT-N66R-16B0:/tmp/share/openpyn-nordvpn# 
 

----- Original Message -----

**Comment by 1951FDG** [comment]
you want to check your python3 installation, basically you are missing some python 3 modules, maybe run ipkg list to see what python packages are available to install

**Comment by spiltmilk1111** [comment]
ok so i have been really busy with school and have given up on the
optware install for now however have installed entware-ng  and
installed not sure if im doing something wrong though.  

According to NordVPN, Least Busy 10 Servers, In SG With 'Load' less
than 70 Which Support OPENVPN-UDP , p2p =  True are : [['sg32', 6],
['sg33', 6], ['sg30', 6], ['sg41', 6], ['sg35', 7], ['sg38', 7],
['sg3', 8], ['sg31', 8], ['sg34', 9], ['sg39', 9]] 

ping: invalid option -- i
BusyBox v1.25.1 (2018-01-28 01:07:48 EST) multi-call binary.

Usage: ping [OPTIONS] HOST

Send ICMP ECHO_REQUEST packets to network hosts

    -4,-6        Force IP or IPv6 name resolution
    -c CNT        Send only CNT pings
    -s SIZE        Send SIZE data bytes in packets
(default:56)
    -t TTL        Set TTL
    -I IFACE/IP    Use interface or IP address as source
    -M hint        Path MTU Discovery strategy [do|want|dont]
    -W SEC        Seconds to wait for the first response
(default:10)
            (after all -c CNT packets are sent)
    -w SEC        Seconds until ping exits (default:infinite)
            (can exit earlier with -c CNT)
    -q        Quiet, only display output at start
            and when finished
    -p        Pattern to use for payload
Ping Failed to: sg32 Skipping it

ping: invalid option -- i
BusyBox v1.25.1 (2018-01-28 01:07:48 EST) multi-call binary.

Usage: ping [OPTIONS] HOST

Send ICMP ECHO_REQUEST packets to network hosts

    -4,-6        Force IP or IPv6 name resolution
    -c CNT        Send only CNT pings
    -s SIZE        Send SIZE data bytes in packets
(default:56)
    -t TTL        Set TTL
    -I IFACE/IP    Use interface or IP address as source
    -M hint        Path MTU Discovery strategy [do|want|dont]
    -W SEC        Seconds to wait for the first response
(default:10)
            (after all -c CNT packets are sent)
    -w SEC        Seconds until ping exits (default:infinite)
            (can exit earlier with -c CNT)
    -q        Quiet, only display output at start
            and when finished
    -p        Pattern to use for payload
Ping Failed to: sg33 Skipping it

----- Original Message -----

**Comment by jotyGill** [comment]
Have you installed the dependencies as specified in the README file?
`opkg install iputils-ping`
and the rest.

**Comment by spiltmilk1111** [comment]
i certainly have

	opkg install git opkg install git-http opkg install iputils-ping opkg
install procps-ng-pgrep opkg install python3 opkg install python3-pip
opkg install sudo opkg install unzip opkg install wget
----- Original Message -----

**Comment by jotyGill** [comment]
Looks like your "ping" is bit old and doesn't take option "-i", I could create an exception and fall back to 1 second wait between pings, if you want.

**Comment by spiltmilk1111** [comment]
Sure

**Comment by jotyGill** [comment]
Its done, test it out by grabbing the 'test' branch.

`sudo pip3 uninstall openpyn`
`git clone --branch test https://github.com/jotyGill/openpyn-nordvpn.git`
`cd openpyn-nordvpn`
`sudo python3 setup.py install`

**Comment by spiltmilk1111** [comment]
Awesome i'll give it a go!!!!!!!!!!!!
 

----- Original Message -----

**Comment by spiltmilk1111** [comment]
root@RT-N66R-16B0:/tmp/share/openpyn-nordvpn# openpyn sg -t 10 --p2p

Running openpyn for the first time? running 'openpyn --update' for you
:) 

--2018-02-19 06:54:10-- 
https://downloads.nordcdn.com/configs/archives/servers/ovpn.zip
Resolving downloads.nordcdn.com.. 104.31.88.109, 104.31.89.109
Connecting to downloads.nordcdn.com|10431.88.109|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 13825195 (13M) [application/zip]
Saving to: '/opt/usr/share/openpyn/ovpn.zip.8'

ovpn.zip.8                                     
100%[=======================================================================================================>] 
13.18M   835KB/s    in 21s     

2018-02-19 06:54:32 (645 KB/s) - '/opt/usr/share/openpyn/ovpn.zip.8'
saved [13825195/13825195]

unzip: invalid option -- u
BusyBox v1.25.1 (2018-01-28 01:07:48 EST) multi-call binary.

Usage: unzip [-lnopq] FILE[.zip] [FILE]... [-x FILE...] [-d DIR]

Extract FILEs from ZIP archive

    -l    List contents (with -q for short form)
    -n    Never overwrite files (default: ask)
    -o    Overwrite
    -p    Print to stdout
    -q    Quiet
    -x FILE    Exclude FILEs
    -d DIR    Extract into DIR
Exception occured while wgetting zip
According to NordVPN, Least Busy 10 Servers, In SG With 'Load' less
than 70 Which Support OPENVPN-UDP , p2p =  True are : [['sg4', 6],
['sg34', 9], ['sg5', 10], ['sg28', 11], ['sg30', 11], ['sg35', 11],
['sg41', 12], ['sg38', 13], ['sg26', 14], ['sg29', 14]] 

Your 'ping' command doesn't support '-i', falling back to wait of 1
second between pings, pings will be slow

Ping Failed to: sg4 Skipping it

Ping Failed to: sg34 Skipping it

Ping Failed to: sg5 Skipping it

Ping Failed to: sg28 Skipping it

Ping Failed to: sg30 Skipping it

Ping Failed to: sg35 Skipping it

Ping Failed to: sg41 Skipping it

Ping Failed to: sg38 Skipping it

Ping Failed to: sg26 Skipping it

Ping Failed to: sg29 Skipping it

Top 0 Servers with best Ping are: []

According to NordVPN, Least Busy 10 Servers, In SG With 'Load' less
than 70 Which Support OPENVPN-UDP , p2p =  True are : [['sg4', 6],
['sg34', 9], ['sg5', 10], ['sg28', 10], ['sg38', 12], ['sg26', 13],
['sg35', 13], ['sg30', 14], ['sg45', 14], ['sg6', 15]] 

Your 'ping' command doesn't support '-i', falling back to wait of 1
second between pings, pings will be slow

Ping Failed to: sg4 Skipping it

	Its done, test it out by grabbing the 'test' branch. 

	sudo pip3 uninstall openpyn
git clone --branch test
https://github.com/jotyGill/openpyn-nordvpn.git
cd openpyn-nordvpn
sudo python3 setup.py install 

	—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub [1], or mute the
thread [2].     

Links:
------
[1]
https://github.com/jotyGill/openpyn-nordvpn/issues/104#issuecomment-366526679
[2]

**Comment by jotyGill** [comment]
Your unzip doesn't support option "-u" darn it busybox! well to be fair, the version 1.25.1 came out in October 2016.
Lets see how it goes, it better work this time, I don't get paid enough for this shii lol.

**Comment by spiltmilk1111** [comment]
Do you accept donations anywhere on github?

All your help is much appreciated!!

Kind regards

Adrian Ellies

**Comment by jotyGill** [comment]
Thank you, Nah mate, just happy to contribute to the open source world :) If want to help, you can help spread the word about Electronic Frontier Foundation (https://www.eff.org) and their efforts to save freedom on internet, you can donate to them. EFF maybe the only organization (nonprofit) with the potential to change the future (I mean prevent the doom) of freedom in the digital world.
Kind Regards
JGill

**Comment by 1951FDG** [comment]
You sure you opkg install unzip

Maybe do a list of installed packages, to double check

And remember that for the router you may be better off using the nvram option and connect using the UI

**Comment by spiltmilk1111** [comment]
inflating: ovpn_tcp/za5.nordvpn.com.tcp.ovpn
  inflating: ovpn_tcp/za6.nordvpn.com.tcp.ovpn
  inflating: ovpn_tcp/za7.nordvpn.com.tcp.ovpn
  inflating: ovpn_tcp/za8.nordvpn.com.tcp.ovpn
  inflating: ovpn_tcp/za9.nordvpn.com.tcp.ovpn
Enter Openpyn options to be stored in initd service file
(/opt/etc/init.d/S23openpyn, Default(Just Press Enter) is, uk : 
uk --max-load 70 --top-servers 10 --pings 5 --skip-dns-patch --nvram 5
--silent

The Following config has been saved in S23openpyn. You can Start it
or/and Stop it with: '/opt/etc/init.d/S23openpyn start',
'/opt/etc/init.d/S23openpyn stop' 

To see usage options type: "openpyn -h" or "openpyn --help"
root@RT-N66R-16B0:/tmp/share/openpyn-nordvpn# openpyn sg -t 10 --p2p
According to NordVPN, Least Busy 10 Servers, In SG With 'Load' less
than 70 Which Support OPENVPN-UDP , p2p =  True are : [['sg39', 10],
['sg40', 16], ['sg3', 20], ['sg8', 20], ['sg31', 20], ['sg27', 20],
['sg34', 20], ['sg41', 20], ['sg36', 21], ['sg44', 23]] 

Your 'ping' command doesn't support '-i', falling back to wait of 1
second between pings, pings will be slow

Ping Failed to: sg39 Skipping it

Ping Failed to: sg40 Skipping it

Ping Failed to: sg3 Skipping it

And remember that for the router you may be better off using the nvram
option and connect using the UI?

not really sure what you mean by this..

sorry for my newbiness.

can you please explain?

Ping Failed to: sg8 Skipping it

Ping Failed to: sg31 Skipping it

Ping Failed to: sg27 Skipping it

Ping Failed to: sg34 Skipping it

Ping Failed to: sg41 Skipping it

Ping Failed to: sg36 Skipping it

Ping Failed to: sg44 Skipping it

Top 0 Servers with best Ping are: []

According to NordVPN, Least Busy 10 Servers, In SG With 'Load' less
than 70 Which Support OPENVPN-UDP , p2p =  True are : [['sg39', 9],
['sg34', 17], ['sg40', 18], ['sg3', 20], ['sg8', 20], ['sg31', 21],
['sg27', 21], ['sg36', 21], ['sg6', 24], ['sg35', 24]] 

Your 'ping' command doesn't support '-i', falling back to wait of 1
second between pings, pings will be slow

Ping Failed to: sg39 Skipping it

 

----- Original Message -----

**Comment by jotyGill** [comment]
closing old thread
