### ISSUE TITLE
AEAD Decrypt error: bad packet ID

### ISSUE THREAD

**Issue by mnt-grrrl** [jotyGill/openpyn-nordvpn#107]
Debian testing openpyn 2.3.1
getting a lot of these errors:
Sun Feb 11 22:28:03 2018 AEAD Decrypt error: bad packet ID (may be a replay): [ #2371 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings

Thanks 
Mnt_grrrl

**Comment by jotyGill** [comment]
This is beyond the scope of openpyn but looks like it's likely that some UDP packets are getting dropped (wifi reception is not that good?). https://airvpn.org/topic/14094-weird-log-entries/

It won't happen if you use "--tcp" but there might be some speed loss.

**Comment by jotyGill** [comment]
BTW, ability to pass through other openvpn options was implemented a while ago.  So if you decide to silence the warning you can do 
`openpyn uk -o '--mute-replay-warnings'`

You would need to update to the latest release.
`sudo pip3 install openpyn --upgrade`

**Comment by norey** [comment]
```
$ openpyn us -o '--mute-replay-warnings'
usage: openpyn [-h] [-v] [--init] [-s SERVER] [--tcp] [-c COUNTRY_CODE]
               [-a AREA] [-d] [-m MAX_LOAD] [-t TOP_SERVERS] [-p PINGS] [-k]
               [-x] [--update] [--skip-dns-patch] [-f]
               [--allow INTERNALLY_ALLOWED [INTERNALLY_ALLOWED ...]]
               [-l [LIST_SERVERS]] [--silent] [--p2p] [--dedicated] [--tor]
               [--double] [--anti-ddos] [--netflix] [--test] [-n NVRAM]
               [-o OPENVPN_OPTIONS] [-loc latitude longitude]
               [country]
openpyn: error: argument -o/--openvpn-options: expected one argument
$ openpyn us -o '--mute-replay-warnings' -a texas
usage: openpyn [-h] [-v] [--init] [-s SERVER] [--tcp] [-c COUNTRY_CODE]
               [-a AREA] [-d] [-m MAX_LOAD] [-t TOP_SERVERS] [-p PINGS] [-k]
               [-x] [--update] [--skip-dns-patch] [-f]
               [--allow INTERNALLY_ALLOWED [INTERNALLY_ALLOWED ...]]
               [-l [LIST_SERVERS]] [--silent] [--p2p] [--dedicated] [--tor]
               [--double] [--anti-ddos] [--netflix] [--test] [-n NVRAM]
               [-o OPENVPN_OPTIONS] [-loc latitude longitude]
               [country]
openpyn: error: argument -o/--openvpn-options: expected one argument
$ openpyn -v
openpyn 2.7.5
```
What am I doing wrong here?
