### ISSUE TITLE
can not download ovpn.zip 

### ISSUE THREAD

**Issue by kangso1** [jotyGill/openpyn-nordvpn#109]
when i init the program, it download ovpn.zip from nordvpn , but the wget error "Unable to establish SSL connection" . i download the file by myself . is that storeing in "/usr/share/openpyn/files" ? then if i unzip in this dir? 
if i was right , i run the program and got an error "There was an ambiguous exception, Check Your Network Connection. forgot to flush iptables? (openpyn -x) " . i do not run any firewall(exp. iptables,firewalld)
my info:
thinkpad t440 ,  i7  8g
ubuntu 16.04
python 3.5

thx

**Comment by jotyGill** [comment]
This is unusual, are you using any proxy? Could possibly be NordVPN's site related temporary issue (is it still happening)?
What version are you running (openpyn -v). 
I just installed the latest version on Ubuntu 16.04 
`sudo pip3 install openpyn --upgrade`
Everything seems to be working fine.
