### ISSUE TITLE
Qustion - lost names resolution

### ISSUE THREAD

**Issue by yuriw** [jotyGill/openpyn-nordvpn#117]
This is pretty cool.
Installed and started VPN very easy.
The problem I am seeing that after establishing VPN connection, I am losing name resolution.
Wonder if there is a solution to it.

Currentely I have:
/etc/resolv.conf 
nameserver 8.8.8.8
nameserver 209.222.18.222
nameserver 209.222.18.218

but tried different combinations.

Thank you!

**Comment by yuriw** [comment]
It could be NordVPN thing but maybe someone figured out how to deal with it...

**Comment by jotyGill** [comment]
What OS and openpyn version are you using? 
when you connect with openpyn, /etc/resolv.conf is supposed to be overwritten.
are you using "-f" option?

**Comment by yuriw** [comment]
I am on ubuntu 16.404 and not using -f

**Comment by yuriw** [comment]
@jotyGill it's a local ubuntu machine, will do when see it again...

**Comment by jotyGill** [comment]
If it's still the case let me know, otherwise lets close this issue.
