### ISSUE TITLE
Support for Advanced Tomato/Tomato Based Routers

### ISSUE THREAD

**Issue by D-s-P** [jotyGill/openpyn-nordvpn#121]
Personally I run Advanced Tomato purely for the nice interface. It would be nice to have this run properly on it. I tried installing but things just aren't working correctly.

I ask this simply because its more difficult to change a vpn on a router that anything else that has better support for it.

This isn't necessary but it would be nice if it were to change what was display in the router settings on the web panel under VPN -> OpenVPNClient.

https://advancedtomato.com/         running on a R-8000

I imagine if I were running a linux system regularly I would use this. Good work.

**Comment by jotyGill** [comment]
Unfortunately, I can't provide any support for Tomato as I don't have any router with it and it may not be feasible at all given the python script currently uses about 30 MB memory to run.
