### ISSUE TITLE
Question - does this script support pfSense ?

### ISSUE THREAD

**Issue by yuriw** [jotyGill/openpyn-nordvpn#124]

**Comment by jotyGill** [comment]
If you have python3 and all dependencies, might need some tweaking but should work. Give it a go. BTW does your pfSence distro have systemd?

**Comment by yuriw** [comment]
I have python2, asking pfSense community for input.  (Little afraid to try on my main router :) )

**Comment by somedevreally** [comment]
@jotyGill does this help?
https://forums.freebsd.org/threads/systemd-alternative-on-freebsd.59932/
