### ISSUE TITLE
Install error on bash (under Windows 10)

### ISSUE THREAD

**Issue by yuriw** [jotyGill/openpyn-nordvpn#133]
Just wondering if this script can run on Windows and/or bash ubuntu 14.04 (Windows 10)?

I am getting this error:

Downloading/unpacking openpyn
  Downloading openpyn-2.4.2.tar.gz (44kB): 44kB downloaded
  Running setup.py (path:/tmp/pip_build_root/openpyn/setup.py) egg_info for package openpyn
    ERROR: openpyn requires Python 3.5 or above.Install using 'pip3' instead of just 'pip'
    Complete output from command python setup.py egg_info:
    ERROR: openpyn requires Python 3.5 or above.Install using 'pip3' instead of just 'pip'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/openpyn
Storing debug log for failure in /home/xxx/.pip/pip.log

**Comment by jotyGill** [comment]
Windows in Not Supported.

**Comment by yuriw** [comment]
This is not really Windows, this is Ubuntu 14.04

**Comment by jotyGill** [comment]
As the error says, you need python >= 3.5

**Comment by yuriw** [comment]
I upgraded to 16.04 but still get errors:

Tue Apr  3 14:54:30 2018 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Tue Apr  3 14:54:30 2018 VERIFY EKU OK
Tue Apr  3 14:54:30 2018 VERIFY OK: depth=0, C=PA, ST=PA, L=Panama, O=NordVPN, OU=NordVPN, CN=us593.nordvpn.com, name=NordVPN, emailAddress=cert@nordvpn.com
Traceback (most recent call last):
  File "/usr/local/bin/openpyn-management", line 9, in <module>
    load_entry_point('openpyn==2.4.2', 'console_scripts', 'openpyn-management')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/openpyn/management/management.py", line 9, in <module>
    gi.require_version('Notify', '0.7')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 102, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Notify not available
Tue Apr  3 14:54:30 2018 Data Channel Encrypt: Cipher 'AES-256-CBC' initialized with 256 bit key

Any clues how to fix them ?

**Comment by jotyGill** [comment]
Try with --silent

**Comment by jotyGill** [comment]
I don't think it's worthwhile to try to get this working in windows env.
