### ISSUE TITLE
IndexError: Looks like you have reached Google maps API's daily request limit. No location data for you :( you could restart your router to get a new IP.

### ISSUE THREAD

**Issue by BobbyBabes** [jotyGill/openpyn-nordvpn#135]
Just installed the cloned repo with `sudo python3 setup.py install`.
Then initialised with default `sudo openpyn --init`.
Connected with `openpyn nl`, and ended up with:
```
Out of the Best Available Servers, Chose nl114
CONNECTING TO SERVER nl114 ON PORT udp
Your OS'linux' Does have '/sbin/resolvconf' using it to update DNS Resolver Entries
```
While I'm connected to `nl114`, I check my IP, do some speedtests and general browsing in Google Chrome. Then I retrieve the US server list with `openpyn -l us`. And receive screens full, from us317 - us1785, but terminated early with `IndexError: Looks like you have reached Google maps API's daily request limit. No location data for you :( you could restart your router to get a new IP.`.
This is just totally impossible.
After this I made 3 other attempts while connected to different VPNs.
Picked a random server from the US list on screen and connected with for example `openpyn -s us1857`. Once connected, I tried `openpyn us -a ny` and  was shown the exact same message.

I had just started my PC, right before installing openpyn-nordvpn. Before this, I had never used the Google Maps API.

**Comment by jotyGill** [comment]
Googlemaps api has been very problematic when sending multiple requests to it (without an account). It tends to block requests quickly. I am switching to Openmaps api now.

**Comment by BobbyBabes** [comment]
I did some reading at the Google Maps website. Would adding a requirement for everyone to generate and use their own Google Maps API key resolve this issue ?
[Google Maps APIs - Get API Key](https://developers.google.com/maps/documentation/timezone/get-api-key)
```
Step 1: Get an API Key from the Google API Console
Click the button below, which guides you through the process of registering a project in the 
Google API Console, activates the Google Maps Time Zone API automatically, and generates 
a generic, unrestricted API key.

Notes
Tip: During development and testing, you can register a project for testing purposes in the 
Google API Console and use a generic, unrestricted API key. When you are ready to move 
your app or website into production, register a separate project for production, create a 
server-restricted API key, and add the key to your application.
```

**Comment by jotyGill** [comment]
I am not going to use or ask other to use, a company like Google's service, where I/they have to annouce to Google who I/they are, everytime we use openpyn.
I am using OpenStreetMaps API now. It does't require any account and seems to be working better that Google's restrictive API. (If you want to try it please do by cloning the 'test' branch)

**Comment by BobbyBabes** [comment]
It was just a question and a suggestion.
I'm not with NordVPN anymore.
I'm trialing vpn.ac (7 days) and perfect-privacy.com (3 days) now.
