### ISSUE TITLE
It's not working on armbian as a VPN router for Netflix

### ISSUE THREAD

**Issue by luisspuerto** [jotyGill/openpyn-nordvpn#137]
Hi! 

I don't know why but it's not working for Netflix, at least while using on cubox-i with armbian as a VPN router. Netflix works when I'm using it on the same device but connecting just with openvpn, but when I'm using openpyn netflix detects that I'm using a VPN and blocks me. 

I've used [this tutorial](https://www.novaspirit.com/2017/06/22/raspberry-pi-vpn-router-w-pia/) to create the forwarding. 

I have also installed pi-hole in the same device. 

If you can shed some light about what could be wrong I'll be glad since the script it's really cool to manage nordvpn on a small device like this. The only thing that seems to not work is Netflix, all the rest works perfectly. 

Thanks!

**Comment by luisspuerto** [comment]
For the sake of testing I try the -force mode and got this error: 

```sh 
$ openpyn us -f --allow 22 80 443
Flushing iptables INPUT and OUTPUT chains AND Applying default Rules
According to NordVPN, Least Busy 10 Servers, In US With 'Load' less than 70 Which Support OPENVPN-UDP are : [['us594', 4], ['us1199', 4], ['us1446', 4], ['us1773', 4], ['us578', 5], ['us598', 5], ['us1202', 5], ['us1209', 5], ['us1424', 5], ['us1426', 5]]

Pinging Server us594 min/avg/max/mdev =  [208, 213, 223, 7]

Pinging Server us1199 min/avg/max/mdev =  [212, 217, 226, 6]

Pinging Server us1446 min/avg/max/mdev =  [229, 230, 231, 0]

Pinging Server us1773 min/avg/max/mdev =  [222, 232, 239, 6]

Pinging Server us578 min/avg/max/mdev =  [212, 222, 228, 6]

Pinging Server us598 min/avg/max/mdev =  [211, 216, 222, 4]

Pinging Server us1202 min/avg/max/mdev =  [212, 222, 233, 8]

Pinging Server us1209 min/avg/max/mdev =  [213, 222, 238, 11]

Pinging Server us1424 min/avg/max/mdev =  [219, 230, 237, 8]

Pinging Server us1426 min/avg/max/mdev =  [226, 237, 243, 7]

Top 10 Servers with best Ping are: ['us594', 'us598', 'us1199', 'us578', 'us1202', 'us1209', 'us1446', 'us1424', 'us1773', 'us1426']


Device "bonding_masters" does not exist.
Traceback (most recent call last):
  File "/usr/local/bin/openpyn", line 11, in <module>
    load_entry_point('openpyn==2.5.0', 'console_scripts', 'openpyn')()
  File "/usr/local/lib/python3.5/dist-packages/openpyn/openpyn.py", line 129, in main
    args.skip_dns_patch, args.silent, args.nvram, args.openvpn_options)
  File "/usr/local/lib/python3.5/dist-packages/openpyn/openpyn.py", line 306, in run
    network_interfaces = get_network_interfaces()
  File "/usr/local/lib/python3.5/dist-packages/openpyn/openpyn.py", line 656, in get_network_interfaces
    interface_out = subprocess.check_output(["ip", "addr", "show", interface])
  File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ip', 'addr', 'show', 'bonding_masters']' returned non-zero exit status 1
```
Perhaps it's relevan.

**Comment by jotyGill** [comment]
Hi, 
Have you tried the option "--netflix"? these servers are supposedly optimized for netflix. Unfortunately if netflix has blacklisted all of them, we can't do anything about it. I would try finding the recently added servers at NordVPN and hope they are not blacklisted yet. These servers are listed here https://support.nordvpn.com/#/General-Info/1047407532/How-to-securely-watch-Netflix-with-NordVPN.htm . 

Try the newer servers, 1774-1781 range for example. 

`openpyn us -s us1774` and so on.
 If the newer ones work, I will exclude the old ones (blacklisted by netfix) and included the latest ones.
The issue with "-f" on raspbian is a different story (souldn't affect you), I will be changing the approach to implement iptables anyway.

**Comment by luisspuerto** [comment]
Hey! 

Thanks for the quick reply. 

Yeah, I tried the option --netflix but without luck. If I put the server manually to one the last ones you, and nordVPN suggests it works. So yeah, it's seems its something related to the server we choose. 

Another problem is, if I try to select manually the server and run the daemon fails because it assumes the server is the name of the country. 

```sh 
$ sudo openpyn US -s us1170 -d

The Following config has been saved in openpyn.service. You can Run it or/and Enable it with: 'sudo systemctl start openpyn', 'sudo systemctl enable openpyn'

 [Unit]
Description=NordVPN connection manager
Wants=network-online.target
After=network-online.target
After=multi-user.target
[Service]
Type=simple
User=root
WorkingDirectory=/usr/local/lib/python3.5/dist-packages/openpyn/
ExecStartPre=/bin/sleep 5
ExecStart=/usr/local/bin/openpyn us1170 --max-load 70 --top-servers 10 --pings 3 --silent
ExecStop=/usr/local/bin/openpyn --kill
StandardOutput=syslog
StandardError=syslog
[Install]
WantedBy=multi-user.target

Started Openpyn by running 'systemctl start openpyn'
To check VPN status, run 'systemctl status openpyn'
```

**Comment by luisspuerto** [comment]
Hey I make it work. 

I really don't know how, but it finally worked. I really think that the issue was just the server. If I choose an specific server that I know work in other devices it also work here. 

Great.
