### ISSUE TITLE
Enable the service at boot with specific parameters

### ISSUE THREAD

**Issue by mbennehar** [jotyGill/openpyn-nordvpn#141]
Hi,
Thank you for this great tool. My question concerns starting the service at boot with certain preferences. Something like a flag, say -b for instance, that enables a systemd service with the provided parameters. So we can do something like "openpyn fr --dedicated -d -b".
Another useful future is to be able to connect to the best server based on certain search criteria. For instance we can list all servers with a dedicated IP address by issuing "openpyn -l --dedicated" but we cannot connect to the best server resulting from the list criteria.

**Comment by jotyGill** [comment]
Hi Thanks,
Both of these functionalities are already in place.
1. "openpyn fr --dedicated -d" creates a systemd service with that specific config. You can enable the service to run at startup with "systemctl enable openpyn".
2. "openpyn fr --dedicated" does exactly what you are after. 

Please read the README for details.

**Comment by mbennehar** [comment]
Humm you're right. Maybe it is just me but I think we should explain this better in the wiki.
Another thing, if I want to connect to the closest server with a dedicated IP address, I need to first search for all servers with 'openpyn -l --dedicated' then select the closest one. To connect to the closest server with a dedicated IP address I need to specify the country first and then select the server.
There should be an option where you don't have to specify the country.
`
openpyn fr --dedicated
There are no servers that satisfy your criteria, please broaden your search.
`

**Comment by mbennehar** [comment]
One more thing, if you try to run openpyn with a specific server '-s server' and the '-d' option the systemd unit dies.
The generated unit is:
` [Unit]

Description=NordVPN connection manager

Wants=network-online.target

After=network-online.target

After=multi-user.target

[Service]

Type=simple

User=root

WorkingDirectory=/usr/local/lib/python3.5/dist-packages/openpyn/

ExecStartPre=/bin/sleep 5

ExecStart=/usr/local/bin/openpyn de70 --max-load 70 --top-servers 10 --pings 3 --silent

ExecStop=/usr/local/bin/openpyn --kill

StandardOutput=syslog

StandardError=syslog

[Install]

WantedBy=multi-user.target`

And the response of 'systemctl status openpyn' is:
`● openpyn.service - NordVPN connection manager

   Loaded: loaded (/etc/systemd/system/openpyn.service; disabled; vendor preset: enabled)

   Active: inactive (dead)
`
