### ISSUE TITLE
Systemd unit doesn't work when manually specifying the server

### ISSUE THREAD

**Issue by mbennehar** [jotyGill/openpyn-nordvpn#142]
Hello again and thank you for the extremely useful tool,
I found one issue. When you manually choose a server and add the -d option to create the openpyn.service systemd file, the unit doesn't work. It is mainly because the generated ExecStart command in the Service section is missing the -s flag. Example :
```bash
ExecStart=/usr/local/bin/openpyn server --max-load 70 --top-servers 10 --pings 3 --silent
```
In order to solve this issue for me I had to override the unit file and add the following to the overriding unit : 
```bash
[Service]
ExecStart=
ExecStart=/usr/local/bin/openpyn -s server --max-load 70 --top-servers 10 --pings 3 --silent
```

**Comment by jotyGill** [comment]
I had already pushed a patch for this in the test branch, for the next release. But as the next release might take some time, I just patched it for 2.5 as well, Cheers
