### ISSUE TITLE
Request to make some changes to use logging module instead

### ISSUE THREAD

**Issue by 1951FDG** [jotyGill/openpyn-nordvpn#150]
I would like to suggest the use of the python logging module instead of using print statements, for colored output we could use https://coloredlogs.readthedocs.io/en/latest/

The reason I want to do this is to be able to use ```Logger.setLevel(level)```, soon I will release the android app, which uses SSH in non interactive mode, and I would like to display the print messages but not all, just critical, error and maybe warning. Also maybe, in the future, to provide an argument for the logging level.

If you agree with the proposed changes, I will make them this weekend, thanks!

**Comment by jotyGill** [comment]
hey!
sounds like a good idea. I just used logging module in an another script dobackup a few days ago.

**Comment by 1951FDG** [comment]
cool, then I'll see to it!

**Comment by jotyGill** [comment]
Hi!
nice work mate, yes I have merged your code (as you would know), and made some further changes. would be good idea for you to merge my test branch back, so it would be easier to merge things in future :)
