### ISSUE TITLE
Really struggling on lubuntu 'address already in use'

### ISSUE THREAD

**Issue by lgjmac** [jotyGill/openpyn-nordvpn#151]
I have to make a ton of requests (8 million) and in order to get around IP blocking, I want to have my python script swap the servers. 

- A random option per country could be useful?
- I can't get it to work even when run from shell... with the following errors
- I have tried running as sudo and not sudo
- Finally: assuming that this is something simple, would the best way to swap servers as currently in a running python script be:
import subprocess
subprocess.call('openpyn -x')
subprocess.call('openpyn us') [possibly using a list of countries to be certain of a new IP address?]
- I pretty much have no idea what I am talking about

Your OS' linux' has systemd-resolve running  using it to update DNS Resolver Entries
Fri May 18 21:46:14 2018 OpenVPN 2.4.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 10 2018
Fri May 18 21:46:14 2018 library versions: OpenSSL 1.1.0g  2 Nov 2017, LZO 2.08
Fri May 18 21:46:14 2018 MANAGEMENT: Socket bind failed on local address [AF_INET]127.0.0.1:7015: Address already in use (errno=98)
Fri May 18 21:46:14 2018 Exiting due to fatal error
Out of the Best Available Servers, Chose us1422
Killed the running openvpn process
CONNECTING TO SERVER us1422 ON PORT udp
os.getlogin(), returned FileNotFoundError, assuming 'openpyn' is running with 'SUDO'
Desktop notifications don't work when using 'sudo', run without it, when asked, provide the sudo credentials

Your OS' linux' has systemd-resolve running  using it to update DNS Resolver Entries
Fri May 18 21:46:15 2018 OpenVPN 2.4.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 10 2018
Fri May 18 21:46:15 2018 library versions: OpenSSL 1.1.0g  2 Nov 2017, LZO 2.08
Fri May 18 21:46:15 2018 MANAGEMENT: Socket bind failed on local address [AF_INET]127.0.0.1:7015: Address already in use (errno=98)
Fri May 18 21:46:15 2018 Exiting due to fatal error
Out of the Best Available Servers, Chose us1095
Killed the running openvpn process
CONNECTING TO SERVER us1095 ON PORT udp
os.getlogin(), returned FileNotFoundError, assuming 'openpyn' is running with 'SUDO'
Desktop notifications don't work when using 'sudo', run without it, when asked, provide the sudo credentials

**Comment by jotyGill** [comment]
yeahh my bad, your script shouldn't need to kill the previous connection manually as I implemented that capability within openpyn. (so I thought, It wasn't killing the openpyn-management properly) I just fixed that in the latest version. Now all you need is to run openpyn in a loop it will take care of killing "openpyn", "openvpn", "openvpn-management"

**Comment by jotyGill** [comment]
I'll close this due to inactivity. It should be fixed
