### ISSUE TITLE
suspend kills internet

### ISSUE THREAD

**Issue by overclockedllama** [jotyGill/openpyn-nordvpn#157]
1. this is amazing and so easy to use i love it!

2. when i suspend my laptop and resume, the internet seems to be blocked by the active vpn connection which lost connection to the server. would there be any way to for example:
 - on suspend use a firewall to block all incoming and outgoing connections and stop the vpn
 - on resume, disable the firewall only for the openvpn ip address and ports, and reconnect to the vpn (hopefully with the same root shell as before to avoid having to retype sudo password) and once successfully connected, disable the firewall

**Comment by overclockedllama** [comment]
this might be of help but i am quite new to systemd so im not entirely sure how it would work:
https://bbs.archlinux.org/viewtopic.php?id=204585 
I think modifying `/etc/systemd/system/suspend@.service` to execute `ufw default deny outgoing; ufw deny incoming; systemctl stop openpyn`

and modify the existing openpyn service adding `After=suspend.target`

**Comment by LKlemens** [comment]
Hi All, I have workaround for it.
```
#!/bin/sh -x
if [ "$1" == "post" ]
then
  kill -9 $(pgrep -x openvpn)
fi
```
that script in /usr/lib/systemd/system-sleep kill openvpn process in postsuspend state, and systemd run that proces again (systemctl enable openpyn), and that reset openvpn and all of it starts works like a charm xD

**Comment by mxovd** [comment]
The system-sleep script makes my dns leak. Maybe because the update resolv.conf script is not run again.
Restarting the whole service might work better.

**Comment by nikolayhg** [comment]
any way to resolve this issue?

**Comment by overclockedllama** [comment]
Maybe use the official nordvpn client as they've now released one. I would trust that more since they are writing it in house and I have observed ip address leaks on this software which I was unable to reproduce on the original client. Closing this as the official client does not have problems with suspend.
