### ISSUE TITLE
trying to reconnect to a stale address

### ISSUE THREAD

**Issue by christopherreay** [jotyGill/openpyn-nordvpn#167]
https://paste.ofcode.org/8B4LUjcsf4wNbY5vjLYq5w

So this happens when I am using a wired connection on my ubuntu machine, and the LAN side of the connection drops, and then reconnects. The openvpn connection does not progress past the last line you see there

If I switch to udp, the connection still attempts to connect to the tcp server, and the UDP messages all fail.

Ive tried killing the openvpn process. 

rebooting the computer works, as does switching to a Wifi connection, for whatever difference that makes!

Thanks for the great tool

Christopher

**Comment by jotyGill** [comment]
closing abandoned issue

**Comment by christopherreay** [comment]
appears to be fixed, never happened again, apologies for not closing the issue
