### ISSUE TITLE
Option to add local network DNS for local translation

### ISSUE THREAD

**Issue by RobinR1** [jotyGill/openpyn-nordvpn#173]
I'm trying to use the openpyn script on a machine in my internal network which also requires access to my internal DNS server for the translation of internal machines. Is there an option to add this internal DNS server to the resolv.conf so that I'm still able to access internal machines by their hostname?

Or is there an option to disable the DNS tunneling all together ? (As my internal DNS server forwards external queries to the nordvpn dns servers anyways (not yet through a tunnel, but that's a WiP :-))

**Comment by jotyGill** [comment]
Yeah, adding an option to use a local DNS server doens't make sense. As you can use any DNS server you like when using --skip-dns-patch but this leaks DNS.
