### ISSUE TITLE
Update VPN credentials from CLI

### ISSUE THREAD

**Issue by mrahmadt** [jotyGill/openpyn-nordvpn#184]
Hello

I'm working in building a basic web interface to control openpyn (plus other apps), what is the best way to pass new VPN credentials to openpyn? 

PS: My credentials are located at /usr/local/lib/python3.6/dist-packages/openpyn/credentials, but I want to know if I have a better way to update it that can work with all users.

**Comment by jotyGill** [comment]
The /usr/local/lib/python3.6/dist-packages/openpyn/ path is OS dependent. openpyn --init finds this using relative path to it. If you were using python, I guess you could import openpyn then get it's __basefilepath__ or directly use credentials.save_credentials().

**Comment by jotyGill** [comment]
I suppose we could add an options like --show-installation-path to get the installation path of openpyn in any system.

**Comment by jotyGill** [comment]
As this has been resolved using the "expect" script. I'll reference it here and close this. 

https://github.com/mrahmadt/SmartGW/tree/master/web/openpyn-setup.sh

[openpyn-setup.zip](https://github.com/jotyGill/openpyn-nordvpn/files/2369081/openpyn-setup.zip)
