### ISSUE TITLE
Autostart and Authentication on daemon service

### ISSUE THREAD

**Issue by mdgcat** [jotyGill/openpyn-nordvpn#191]
First of all, this is great work you're doing here.  Secondly, I'm trying to add the daemon service and autostart on boot.

Command I ran was:
`sudo openpyn us --area "Seattle" --tcp -d`

It really doesn't autostart on boot until I authenticate through a dialog box.
![screenshot from 2018-08-31 20-08-25](https://user-images.githubusercontent.com/9360981/44941823-66504a80-ad5a-11e8-83ce-6c2501433023.png)

By the way that dialog box opens up **every** time I start a new terminal.  And also other programs like the Atom editor.   The re-authentication process doesn't disturb or interrupt the initial daemon from running.  Even if I hit cancel on the subsequent dialog boxes.

I'm running Ubuntu 16.04.5 LTS.  Should I have not run `sudo` on the command?  Is there a quick fix for this?

**Comment by jotyGill** [comment]
Thanks,

ok this is weird, when we run `sudo openpyn -d` it basically creates a openpyn.service file in  /etc/systemd/system/ then starts the service by running `sudo systemctl start openpyn`. if you want it to autorun it on system startup just enable it once by typing `sudo systemctl enable openpyn`. Is that what you did? It shouldn't ask for any password afterwords.

**Comment by mdgcat** [comment]
Ooops! I went through the bash history and I found out what I did.  I could not figure out how to autostart, so I put `systemctl start openpyn` in my `bashrc`.  **LOL** I don't know why I did this. `sudo systemctl enable openpyn` is working and I have autostart now.

Thanks for all your effort.  Now that I totally embarrass myself like a noob, you can close this issue and I'll see myself out.

**Comment by jotyGill** [comment]
haha, We all have our moments. As long as it worked out in the end :)
