### ISSUE TITLE
There was an ambiguous exception, Check Your Network Connection.

### ISSUE THREAD

**Issue by arichiardi** [jotyGill/openpyn-nordvpn#198]
Hi!

I have recently bumped ubuntu to 18.04 and after that `openpyn` started reporting this:

```
There was an ambiguous exception, Check Your Network Connection. forgot to flush iptables? (openpyn -x)
```

No matter what I do or how I start it always pops up.

What can I do to debug more? I am comfortable in executing anything but do not know `python` that well so any advice is welcome!

**Comment by jotyGill** [comment]
Hi there,
So at what stage the error pops up. The error is thrown by 'requests' module in python. Basically it can't make a https connection for some reason. First I would uninstall openpyn and install the latest version. If your version is >2.7.0 there should be logs in /var/log/openpyn/. Are you using '-f' option or any firewall rules? Check if your ISP, country blocking access to nordVPN or api.nordvpn.com. Or NordVPN is blocking your IP, or could be some networking/OS issue.

**Comment by arichiardi** [comment]
Thank you! will try those in sequence and report back.

Can the ISP block NordVPN? I mean all of their servers?

**Comment by jotyGill** [comment]
Well, we need access to downloads.nordcdn.com to download configs. api.nordvpn.com to get info about servers. Not having access to one will break it. if you are using their DNS yes easily they could block acess to "*.nordvpn.com", If they wanted to.
More likely it's something else.

**Comment by arichiardi** [comment]
The `openpyn --init` worked so I assumed it was still freely accessible. Anyways, will try things :smile:

**Comment by arichiardi** [comment]
I am tailing the logs but unfortunately I only see:

```
2018-09-20 21:14:41,152 [NOTICE] Root access needed to modify 'iptables' rules
2018-09-20 21:14:41,153 [INFO] Flushing iptables INPUT and OUTPUT chains AND Applying default Rules
2018-09-20 21:14:50,080 [INFO] Re-enabling ipv6
2018-09-20 21:14:53,633 [ERROR] There was an ambiguous exception, Check Your Network Connection. forgot to flush iptables? (openpyn -x)
```

The previous lines are me doing `openpyn -x`, to no avail.

I am on version `2.7.5`.

**Comment by arichiardi** [comment]
Does this change the diagnosis?

```
$ http GET https://api.nordvpn.com/server

http: error: SSLError: HTTPSConnectionPool(host='api.nordvpn.com', port=443): Max retries exceeded with url: /server (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)'))) while doing GET request to URL: https://api.nordvpn.com/server
```

**Comment by jotyGill** [comment]
In that case I might be wrong. Then it's probably your DNS/ISP blocking it.
Use dig to find out if it is indeed the case.
`dig @your-old-dns api.nordvpn.com`

**Comment by arichiardi** [comment]
Thanks a lot for the neat `dig` trick as well. Closing this one as changing the DNS solved it.
