### ISSUE TITLE
Question about configuration/usage

### ISSUE THREAD

**Issue by Jorman** [jotyGill/openpyn-nordvpn#205]
Hi, I just installed debian on my nas, so finally I can use all the potential of this tool!

I installed it then I configure it with:
`openpyn it -t 10 --p2p -d`
and for example connect to server 12

So now what happen if:
1. The server 12 is not the less load server?
2. The connection to vpn go down? 

So I've to configure some file or make a cron in order to be sure that the vpn is on and connected to the best server?

Any suggestion?

Jo

**Comment by jotyGill** [comment]
I missed this one.

1. As there's no continious monitoring server loads only matter when connecting.
2. If openvpn declares that the tunnel is down, openpyn tries to connect to the next best server it found.
