### ISSUE TITLE
Connecting via SSH and VNC to a droplet with an active VPN connection

### ISSUE THREAD

**Issue by nittolese** [jotyGill/openpyn-nordvpn#214]
Hi,
first of all, thanks for this amazing project. It works like a charm.

I have only a problem: I would connect via SSH or/and VNC to a droplet (DigitalOcean) with an active VPN connection. I need this because I'm going to rotate VPN connections programmatically without lose my current connection (SSH/VNC).

Whenever I start a VPN connection via openpyn (also playing with -f or --allow 22 parameters) but then I am locked out from my server until reboot.

Tried googling about routing (i.e. https://www.linode.com/community/questions/7381/openvpn-client-connected-to-a-server-while-listening-to-ssh#answer-36662 ) the SSH and VNC connections through the default interface but can't resolve this issue.

Any help on this?
I am using a droplet with Ubuntu 18.04.

Thanks!

**Comment by BlackArbsCEO** [comment]
> Hi,
> first of all, thanks for this amazing project. It works like a charm.
> 
> I have only a problem: I would connect via SSH or/and VNC to a droplet (DigitalOcean) with an active VPN connection. I need this because I'm going to rotate VPN connections programmatically without lose my current connection (SSH/VNC).
> 
> Whenever I start a VPN connection via openpyn (also playing with -f or --allow 22 parameters) but then I am locked out from my server until reboot.
> 
> Tried googling about routing (i.e. https://www.linode.com/community/questions/7381/openvpn-client-connected-to-a-server-while-listening-to-ssh#answer-36662 ) the SSH and VNC connections through the default interface but can't resolve this issue.
> 
> Any help on this?
> I am using a droplet with Ubuntu 18.04.
> 
> Thanks!

Did you ever solve this issue? I'm having the same problem.
