### ISSUE TITLE
Completely remove openpyn, to re-install (Raspberry Pi 3B+)

### ISSUE THREAD

**Issue by waleedqq** [jotyGill/openpyn-nordvpn#220]
After flashing and installing Raspian from scratch I followed these steps, exactly:

- Install dependencies `sudo apt install openvpn unzip wget python3-setuptools python3-pip psmisc`
-  Install python wheel, required for openpyn install `sudo python3 -m pip install wheel --upgrade`
- Install openpyn: `sudo python3 -m pip install openpyn --upgrade`
- Execute the openpyn initialization. This will request your NordVPN credentials, download the ovpn configfiles and install a systemd service): `sudo openpyn --init`
- Enable the system service to start on boot: `sudo systemctl enable openpyn`
- Start the VPN: `sudo systemctl start openpyn`

The VPN was working, and I just set and forgot it. I have come back after doing some other work around building a media server to find the VPN stopped working on boot and is refused to start even after using the `sudo systemctl start openpyn` command. I have done too much up my Pi to re-flash a fresh copy so hoping to remove openpyn and re-install.

**Comment by jotyGill** [comment]
Hi, 
uninstall it using,
`sudo pip3 uninstall openpyn`
if for some reason it doesn't fully uninstall find where it is installed on your OS with.
`python3 -m site`
that would tell you python package locations. it would probably be something like `/usr/local/lib/python3.5/site-packages/`
you can delete openpyn folder there as well the `/usr/local/bin/openpyn`

To install,
`sudo python3 -m pip install openpyn -U`
