### ISSUE TITLE
8.8.8.8 configurable?

### ISSUE THREAD

**Issue by wickedsp1d3r** [jotyGill/openpyn-nordvpn#222]
Could [8.8.8.8](https://github.com/jotyGill/openpyn-nordvpn/blob/master/openpyn/openpyn.py#L512) be added as configurable option? I would like to use my own choice there.
Thanks.

**Comment by jotyGill** [comment]
Could you please elaborate. I think you mean you want to use 8.8.8.8 as the DNS not NordVPN's DNS?
Currently no.
NordVPN's DNS are put in there to ensure the system doens't use OS's default DNS (your router's internal IP or 127.0.0.1, which again would be going to your router)
Is there any specific advantage of adding additional option to configure DNS address?
