### ISSUE TITLE
Root access needed to kill 'openpyn-management' process

### ISSUE THREAD

**Issue by Aquassarim** [jotyGill/openpyn-nordvpn#223]
Hello,
first of all, thank you for this program, it's magic !
I just have a question, I don't know if it's an issue or not...

When I run:
    openpyn fr (with or without other options)
just after openpyn has determined the better server, I am asked to give rot access through this line:
    [date] [NOTICE] Root access needed to kill 'openpyn-management' process
and indeed, if I run:
    ps -aux | grep openpyn-management
I can see that root tries to 'sudo killall openpyn-management' (that was not here before the run of the command).

I just wonder if it's normal or not since it is not mentioned  in the given examples.
I have the same behaviour with:
    openpyn -k

Thank you for your help!

**Comment by jotyGill** [comment]
Thank you for the kind words.
yes this is intended. any previously running openpyn and openvpn instance is killed at the start. openpyn-management is the script that allows us to display connected/disconnected notifications.
