### ISSUE TITLE
TCP recv error: Connection reset by peer

### ISSUE THREAD

**Issue by anti4r** [jotyGill/openpyn-nordvpn#224]
Hey, I get this error when trying to start up and i cant tell why (Arch Linux).

`~~~> openpyn us`

According to NordVPN, Least Busy 10 Servers in US With 'Load' Less Than 70 Which Support OPENVPN-UDP Are: [['us2008', 5], ['us2186', 5], ['us1776', 6], ['us2003', 6], ['us2021', 6], ['us2199', 6], ['us3106', 6], ['us1091', 7], ['us1423', 7], ['us1512', 7]]

Pinging Server us2008 min/avg/max/mdev = [67, 68, 69, 0] 

Pinging Server us2186 min/avg/max/mdev = [67, 69, 70, 1] 

Pinging Server us1776 min/avg/max/mdev = [63, 64, 64, 0] 

Pinging Server us2003 min/avg/max/mdev = [72, 73, 74, 0] 

Pinging Server us2021 min/avg/max/mdev = [67, 69, 70, 1] 

Pinging Server us2199 min/avg/max/mdev = [68, 69, 69, 0] 

Pinging Server us3106 min/avg/max/mdev = [70, 72, 74, 1] 

Pinging Server us1091 min/avg/max/mdev = [69, 71, 72, 1] 

Pinging Server us1423 min/avg/max/mdev = [65, 66, 67, 0] 

Pinging Server us1512 min/avg/max/mdev = [33, 34, 36, 1] 

Top 10 Servers with Best Ping Are: ['us1512', 'us1776', 'us1423', 'us2008', 'us2199', 'us2186', 'us2021', 'us1091', 'us3106', 'us2003']

Out of the Best Available Servers, Chose us1512

2019-01-30 15:48:47 [SUCCESS] CONNECTING TO SERVER us1512 ON PORT udp
2019-01-30 15:48:47 [SUCCESS] Your OS 'linux' Does have '/sbin/resolvconf', using it to update DNS Resolver Entries
Wed Jan 30 15:48:47 2019 WARNING: Using --management on a TCP port WITHOUT passwords is STRONGLY discouraged and considered insecure
Wed Jan 30 15:48:47 2019 OpenVPN 2.4.6 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Apr 24 2018
Wed Jan 30 15:48:47 2019 library versions: OpenSSL 1.1.1a  20 Nov 2018, LZO 2.10
Wed Jan 30 15:48:47 2019 MANAGEMENT: TCP Socket listening on [AF_INET]127.0.0.1:7015
Wed Jan 30 15:48:47 2019 WARNING: --ping should normally be used with --ping-restart or --ping-exit
Wed Jan 30 15:48:47 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Wed Jan 30 15:48:47 2019 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Wed Jan 30 15:48:47 2019 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Wed Jan 30 15:48:47 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]207.89.23.91:1194
Wed Jan 30 15:48:47 2019 Socket Buffers: R=[212992->212992] S=[212992->212992]
Wed Jan 30 15:48:47 2019 UDP link local: (not bound)
Wed Jan 30 15:48:47 2019 UDP link remote: [AF_INET]207.89.23.91:1194
Wed Jan 30 15:48:47 2019 TLS: Initial packet from [AF_INET]207.89.23.91:1194, sid=028dfe43 0a63f281
Wed Jan 30 15:48:47 2019 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Wed Jan 30 15:48:47 2019 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA
Wed Jan 30 15:48:47 2019 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA3
Wed Jan 30 15:48:47 2019 VERIFY KU OK
Wed Jan 30 15:48:47 2019 Validating certificate extended key usage
Wed Jan 30 15:48:47 2019 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Wed Jan 30 15:48:47 2019 VERIFY EKU OK
Wed Jan 30 15:48:47 2019 VERIFY OK: depth=0, CN=us1512.nordvpn.com
Wed Jan 30 15:48:47 2019 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 2048 bit RSA
Wed Jan 30 15:48:47 2019 [us1512.nordvpn.com] Peer Connection Initiated with [AF_INET]207.89.23.91:1194
Wed Jan 30 15:48:48 2019 MANAGEMENT: Client connected from [AF_INET]127.0.0.1:7015
Wed Jan 30 15:48:48 2019 SENT CONTROL [us1512.nordvpn.com]: 'PUSH_REQUEST' (status=1)
Wed Jan 30 15:48:50 2019 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1,sndbuf 524288,rcvbuf 524288,dhcp-option DNS 103.86.96.100,dhcp-option DNS 103.86.99.100,comp-lzo no,route-gateway 10.8.8.1,topology subnet,ping 60,ping-restart 180,ifconfig 10.8.8.50 255.255.255.0,peer-id 39,cipher AES-256-GCM'
Wed Jan 30 15:48:50 2019 OPTIONS IMPORT: timers and/or timeouts modified
Wed Jan 30 15:48:50 2019 OPTIONS IMPORT: compression parms modified
Wed Jan 30 15:48:50 2019 OPTIONS IMPORT: --sndbuf/--rcvbuf options modified
Wed Jan 30 15:48:50 2019 Socket Buffers: R=[212992->425984] S=[212992->425984]
Wed Jan 30 15:48:50 2019 OPTIONS IMPORT: --ifconfig/up options modified
Wed Jan 30 15:48:50 2019 OPTIONS IMPORT: route options modified
Wed Jan 30 15:48:50 2019 OPTIONS IMPORT: route-related options modified
Wed Jan 30 15:48:50 2019 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Wed Jan 30 15:48:50 2019 OPTIONS IMPORT: peer-id set
Wed Jan 30 15:48:50 2019 OPTIONS IMPORT: adjusting link_mtu to 1657
Wed Jan 30 15:48:50 2019 OPTIONS IMPORT: data channel crypto options modified
Wed Jan 30 15:48:50 2019 Data Channel: using negotiated cipher 'AES-256-GCM'
Wed Jan 30 15:48:50 2019 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Wed Jan 30 15:48:50 2019 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Wed Jan 30 15:48:50 2019 ROUTE_GATEWAY 192.168.1.1/255.255.255.0 IFACE=wlo1 HWADDR=d0:57:7b:f3:df:4f
Wed Jan 30 15:48:50 2019 TUN/TAP device tun0 opened
Wed Jan 30 15:48:50 2019 TUN/TAP TX queue length set to 100
Wed Jan 30 15:48:50 2019 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Wed Jan 30 15:48:50 2019 /usr/bin/ip link set dev tun0 up mtu 1500
Wed Jan 30 15:48:50 2019 /usr/bin/ip addr add dev tun0 10.8.8.50/24 broadcast 10.8.8.255
Wed Jan 30 15:48:50 2019 /usr/lib/python3.7/site-packages/openpyn/scripts/update-resolv-conf.sh tun0 1500 1585 10.8.8.50 255.255.255.0 init
dhcp-option DNS 103.86.99.100
dhcp-option DNS 103.86.96.100
dhcp-option DNS 208.67.222.220
Wed Jan 30 15:48:50 2019 /usr/bin/ip route add 207.89.23.91/32 via 192.168.1.1
Wed Jan 30 15:48:50 2019 /usr/bin/ip route add 0.0.0.0/1 via 10.8.8.1
Wed Jan 30 15:48:50 2019 /usr/bin/ip route add 128.0.0.0/1 via 10.8.8.1
Wed Jan 30 15:48:50 2019 Initialization Sequence Completed
Traceback (most recent call last):
  File "/usr/bin/openpyn-management", line 11, in <module>
    load_entry_point('openpyn==2.7.5', 'console_scripts', 'openpyn-management')()
  File "/usr/lib/python3.7/site-packages/openpyn/management/management.py", line 166, in main
    return show(args.do_notify)
  File "/usr/lib/python3.7/site-packages/openpyn/management/management.py", line 68, in show
    notification.show()
gi.repository.GLib.Error: g-io-error-quark: Error calling StartServiceByName for org.freedesktop.Notifications: Timeout was reached (24)
Wed Jan 30 15:49:13 2019 MANAGEMENT: TCP recv error: Connection reset by peer
Wed Jan 30 15:49:13 2019 MANAGEMENT: Client disconnected
`

**Comment by jotyGill** [comment]
run it with `--silent`. with your setup the notifications are not working properly.
