### ISSUE TITLE
parrallel pings

### ISSUE THREAD

**Issue by christopherreay** [jotyGill/openpyn-nordvpn#241]
### Parrallel pings

When I am travelling I often find that I am connecting repeatedly to different wifi's or more likely after putting my laptop into suspend.

Because of this I find waiting for the pings to 10 servers takes slightly longer than feels right to my flow.

I would like to implement sending the pings to the servers in parrallel with each other.

#### implementation design decisions 
* change: `def ping_servers(better_servers_list: List, pings: str, stats: bool) -> List`:
  * [x] - Implement sending pings to servers in parrallel
  * [x] - ~~default to send pings in parallel add option to send in series~~
    * series pings removed completely

#### questions / discussion
* are there any reasons not to send the pings in parrallell?
  * perhaps may use more ram than is suitable for openpyn running on router hardware
* is there any case where a "fallback" to sending pings in series is required?

#### state of implementation
* [x] - ~~ implement parallel pings with tests ~~

**Comment by jotyGill** [comment]
Cheers mate. Sounds good to me :)
The only potential problem we could have is resourse usage on WRT routers. I don't know how much ram it would use to implement threading?
That's the only case we might need to fall back.

**Comment by christopherreay** [comment]
OK, so for now default to serial, and make an option for parrallel?

**Comment by jotyGill** [comment]
I guess we go default with parallel. If it's a problem then we'll see.

**Comment by jotyGill** [comment]
Also could please make sure to pull all my commits in the 'test' branch first. Cheers

**Comment by christopherreay** [comment]
so use the test branch as the base?

**Comment by christopherreay** [comment]
yessir !

**Comment by jotyGill** [comment]
Yes plz.

**Comment by christopherreay** [comment]
okay coke

**Comment by christopherreay** [comment]
I wonder if the multithreading can be done only in the OS, rather than in python. Will check it out

**Comment by jotyGill** [comment]
we just need to run some subprocess commands in parallel and capture their output later.
something like this?
https://stackoverflow.com/questions/23818569/run-subprocesses-in-parallel

**Comment by christopherreay** [comment]
Hello :)

Ive got the parallel pings running. I have to tidy up and finish it off for the pull request.

The other thing that takes time is the -f option dhcp things. Is there a way of doing that faster? What is it called? Lets open an issue about it?

**Comment by christopherreay** [comment]
I had to put a 0.01 second delay between the subprocess.Popen calls to ping, because otherwise packets were dropped for "no reason". It is satisfyingly quicker.

The sequential option is implemented as "-S --sequential"
