### ISSUE TITLE
Change to MTU and Network Settings Issue

### ISSUE THREAD

**Issue by danner26** [jotyGill/openpyn-nordvpn#264]
Recently I have changed some settings on my network/machine that enables jumbo frames, and some other services. Here is what was changed:
MTU set to 9000

Sysctl:
net.core.wmem_max = 12582912
net.core.rmem_max = 12582912
net.ipv4.tcp_rmem = 10240 87380 12582912
net.ipv4.tcp_wmem = 10240 87380 12582912
net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_timestamps = 1
net.ipv4.tcp_sack = 1
net.ipv4.tcp_no_metrics_save = 1
net.core.netdev_max_backlog = 5000

I am not sure if these are affecting openpyn or not, but here is the issue. I have run the update command as well as removed and reinstalled openpyn. When I run the command I usually do: `/usr/local/bin/openpyn us  --update --p2p` I get the following error: `2020-04-07 09:58:48 [ERROR] There are no servers that satisfy your criteria, please broaden your search.`
So okay, I will try any available US server: `openpyn us --update` and I get the same error

No matter what I try, even if I try other areas/countries I get the same error. Any ideas?

**Comment by cdoycod** [comment]
Same error here.... with or without changing settings on sysctl.conf

**Comment by danner26** [comment]
@cdoycod I didnt check this before, the API appears to be down/returning null data
curl --silent https://api.nordvpn.com/server
returns an empty data set

**Comment by danner26** [comment]
This seems to be resolved for me.
