### ISSUE TITLE
"There are no servers that satisfy your criteria, please broaden your search"

### ISSUE THREAD

**Issue by SolGN** [jotyGill/openpyn-nordvpn#265]
Hello there,

I'm new to linux but I've got a small experience of terminal in mac & a little bit of shell... 
I find your program very very interesting as I'm trying to run NordVPN through it.
Installation & init goes well but when trying to connect I've got that message

` There are no servers that satisfy your criteria, please broaden your search.`

and for some other servers I've got this :
```
2020-04-07 19:44:18 [NOTICE] VPN configuration file /usr/local/lib/python3.7/dist-packages/openpyn/files/ovpn_udp/fr.nordvpn.com.udp.ovpn doesn't exist, don't worry running 'openpyn --update' for you :)
2020-04-07 19:44:24 [NOTICE] Root access needed to write files in '/usr/local/lib/python3.7/dist-packages/openpyn/files/'
```
which had me prompting the same but with sudo giving this : 
```

2020-04-07 19:46:09 [SUCCESS] CONNECTING TO SERVER fr ON PORT udp
2020-04-07 19:46:09 [WARNING] Desktop notifications don't work when using 'sudo', run without it, when asked, provide the sudo credentials
2020-04-07 19:46:09 [SUCCESS] Your OS 'linux' has systemd-resolve running, using it to update DNS Resolver Entries
Options error: In [CMD-LINE]:1: Error opening configuration file: /usr/local/lib/python3.7/dist-packages/openpyn/files/ovpn_udp/fr.nordvpn.com.udp.ovpn
Use --help for more information.

```
I've tried to run --update or to init again but it does not solve the issue. Whether the server choosen (uk,us;fr;it;au;ca) it does not work

My newbie guess is something about permisison to access the server list file or something like that
Do you have any idea ? 

By the way I previously had the nordvpn terminal client which I removed, He was working but I prefer your openpyn ;) 

Thank you for your help, regards

Solal

**Comment by churizzle** [comment]
I was about to post this. I am also have the same issue. 

:/etc/openvpn/ovpn_udp $ sudo systemctl status openpyn
● openpyn.service - NordVPN connection manager
   Loaded: loaded (/etc/systemd/system/openpyn.service; enabled; vendor preset:
enabled)
  Drop-In: /etc/systemd/system/openpyn.service.d
           └─dietpi-services_edit.conf
   Active: failed (Result: exit-code) since Tue 2020-04-07 14:28:26 E
DT; 7s ago
  Process: 9186 ExecStartPre=/bin/sleep 5 (code=exited, status=0/SUCCESS)
  Process: 9192 ExecStart=/usr/local/bin/openpyn ca --max-load 70 --top-servers
10 --pings 3 (code=exited, status=1/FAILURE)
 Main PID: 9192 (code=exited, status=1/FAILURE)

Apr 07 14:28:17 pi systemd[1]: Starting NordVPN connection manager...
Apr 07 14:28:22 pi systemd[1]: Started NordVPN connection manager.
Apr 07 14:28:26 pi openpyn[9192]: 2020-04-07 14:28:26 [ERROR] There are no serve
rs that satisfy your criteria, please broaden your search.
Apr 07 14:28:26 pi openpyn[9192]: There are no servers that satisfy your criteri
a, please broaden your search.
Apr 07 14:28:26 pi systemd[1]: openpyn.service: Main pro
cess exited, code=exited, status=1/FAILURE
Apr 07 14:28:26 pi systemd[1]: openpyn.service: Failed w
ith result 'exit-code'.

**Comment by SolGN** [comment]
> I was about to post this. I am also have the same issue.
> 
> :/etc/openvpn/ovpn_udp $ sudo systemctl status openpyn
> ● openpyn.service - NordVPN connection manager
> Loaded: loaded (/etc/systemd/system/openpyn.service; enabled; vendor preset:
> enabled)
> Drop-In: /etc/systemd/system/openpyn.service.d
> └─dietpi-services_edit.conf
> Active: failed (Result: exit-code) since Tue 2020-04-07 14:28:26 E
> DT; 7s ago
> Process: 9186 ExecStartPre=/bin/sleep 5 (code=exited, status=0/SUCCESS)
> Process: 9192 ExecStart=/usr/local/bin/openpyn ca --max-load 70 --top-servers
> 10 --pings 3 (code=exited, status=1/FAILURE)
> Main PID: 9192 (code=exited, status=1/FAILURE)
> 
> Apr 07 14:28:17 pi systemd[1]: Starting NordVPN connection manager...
> Apr 07 14:28:22 pi systemd[1]: Started NordVPN connection manager.
> Apr 07 14:28:26 pi openpyn[9192]: 2020-04-07 14:28:26 [ERROR] There are no serve
> rs that satisfy your criteria, please broaden your search.
> Apr 07 14:28:26 pi openpyn[9192]: There are no servers that satisfy your criteri
> a, please broaden your search.
> Apr 07 14:28:26 pi systemd[1]: openpyn.service: Main pro
> cess exited, code=exited, status=1/FAILURE
> Apr 07 14:28:26 pi systemd[1]: openpyn.service: Failed w
> ith result 'exit-code'.

Do you now since when do you have this issue because if it is recent, it might be a temporary serve

**Comment by SolGN** [comment]
> I was about to post this. I am also have the same issue.
> 
> :/etc/openvpn/ovpn_udp $ sudo systemctl status openpyn
> ● openpyn.service - NordVPN connection manager
> Loaded: loaded (/etc/systemd/system/openpyn.service; enabled; vendor preset:
> enabled)
> Drop-In: /etc/systemd/system/openpyn.service.d
> └─dietpi-services_edit.conf
> Active: failed (Result: exit-code) since Tue 2020-04-07 14:28:26 E
> DT; 7s ago
> Process: 9186 ExecStartPre=/bin/sleep 5 (code=exited, status=0/SUCCESS)
> Process: 9192 ExecStart=/usr/local/bin/openpyn ca --max-load 70 --top-servers
> 10 --pings 3 (code=exited, status=1/FAILURE)
> Main PID: 9192 (code=exited, status=1/FAILURE)
> 
> Apr 07 14:28:17 pi systemd[1]: Starting NordVPN connection manager...
> Apr 07 14:28:22 pi systemd[1]: Started NordVPN connection manager.
> Apr 07 14:28:26 pi openpyn[9192]: 2020-04-07 14:28:26 [ERROR] There are no serve
> rs that satisfy your criteria, please broaden your search.
> Apr 07 14:28:26 pi openpyn[9192]: There are no servers that satisfy your criteri
> a, please broaden your search.
> Apr 07 14:28:26 pi systemd[1]: openpyn.service: Main pro
> cess exited, code=exited, status=1/FAILURE
> Apr 07 14:28:26 pi systemd[1]: openpyn.service: Failed w
> ith result 'exit-code'.

Ow that's interessting what system are you on ?

PS: Sorry for close then reopened ... it was manipulation error

**Comment by Firebug24k** [comment]
Me too, openpyn quit working today after working for months.  Same problem.

**Comment by fcambria83** [comment]
Nordvpn api doesn't work:
https://api.nordvpn.com/server call return null instead of the list of servers in json format!

**Comment by fcambria83** [comment]
At the moment in order to connect to Nordvpn, you must indicate a specific server:
i.e.:
openpyn -s it160

**Comment by SolGN** [comment]
Okay

Thank you very much ! Issue resolved then ;) 
Hope it will work again soon
