### ISSUE TITLE
Fails on Debian streach

### ISSUE THREAD

**Issue by mygnu** [jotyGill/openpyn-nordvpn#28]
CONNECTING TO SERVER de111  ON PORT tcp443
Your OS  debian Does not have '/sbin/resolvconf': Manually Applying Patch to Tunnel DNS Through The VPN Tunnel By Modifying '/etc/resolv.conf'
**sudo: /usr/share/openpyn/manual-dns-patch.sh: command not found**  _** this file doesn't exist becouse pip is installing it somewhere else maybe**_
Sun Jun 11 00:07:53 2017 OpenVPN 2.4.0 [git:master/d73f7253d939e293+] x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 22 2017
Sun Jun 11 00:07:53 2017 library versions: OpenSSL 1.0.2l  25 May 2017, LZO 2.08
Sun Jun 11 00:07:53 2017 Error reading username from Auth authfile: /usr/share/openpyn/credentials
Sun Jun 11 00:07:53 2017 Exiting due to fatal error

**Comment by mygnu** [comment]
drwxr-xr-x 1 root root   32 Jun 11 00:03 .
drwxr-xr-x 1 root root 4.9K Jun 11 00:11 ..
-rw------- 1 root root    0 Jun 11 00:01 credentials
drwxr-xr-x 1 root root 124K Jun 11 00:01 files
➜  openpyn pwd
/usr/share/openpyn

**Comment by jotyGill** [comment]
Is this a fresh install using pip3 (with sudo)?

**Comment by jotyGill** [comment]
There seems to be inconsistent behavior using pip on Debian Stretch. There implementation is not allowing the script to install files in '/usr/share/openpyn'. Clone the repo and install it using:
'sudo python3 setup.py install'
