### ISSUE TITLE
Openpyn Autostart on Debian

### ISSUE THREAD

**Issue by larry77** [jotyGill/openpyn-nordvpn#286]
Dear All,
Not really an issue but a question.
I upgraded and reinitialized openpyn to version 3.

`$ sudo systemctl start openpyn

$ sudo systemctl enable openpyn
Created symlink /etc/systemd/system/multi-user.target.wants/openpyn.service → /etc/systemd/system/openpyn.service.`

Now nordvpn autostarts with the saved configuration every time I boot my machine.
If I want to change this behaviour, i.e. I do not want openpyn to establish automatically a connection to nordvpn when I log into my machine, what am I supposed to do?
Many thanks!

**Comment by Serrgee** [comment]
Hello,

Disable autostart by the command:
`sudo systemctl disable openpyn`

**Comment by larry77** [comment]
Thanks!
