### ISSUE TITLE
option to not patch DNS ips

### ISSUE THREAD

**Issue by mygnu** [jotyGill/openpyn-nordvpn#30]
I have setup my router to use nordvpn dns so no need to patch at pc level. please add the option to not touch dns

**Comment by jotyGill** [comment]
I can provide an option to skip that, I see a scenario when it would be desired: if you have an internal DNS server and you absolutely need to resolve internal site names using it while using openpyn. Be aware your DNS traffic will go through your ISP, UNENCRYPTED.
I don't suppose that's your goal here. Even if you have configured your router to use Nord's DNS, By defualt your router would be the DNS server itself, forwarding unencrypted DNS traffic to Nord. You could fix that by directly specifying the DNS servers (to be used by clients) in your DHCP server(router), but then you wouldn't be able to resolve internal site's IPs (if that was your goal).

I am thinking of creating a functionality like profiles, where one could specify scripts behavior, I will probably put an option to skip DNS patching there.

**Comment by jackgu1988** [comment]
I am using DNSSec and /etc/resolv.conf only contains 127.0.0.1.

You have done an excellent job here, but I would like an option to not change my DNS configuration. What you are doing should probably be kept as the default configuration, but we should also have the option to skip it.

If I find time I can implement it, but I don't see this happening within the next month or so.

**Comment by jotyGill** [comment]
Thank you. Yeah, I was using DNSSec a while ago and realised that. See the current setup when using "-f" doesn't allow DNS on loopback(it's there to stop dns fallback to 127.0.0.1), so I will also have to allow that when skipping DNS patching as well. No worries, I'll sort it out.

**Comment by jotyGill** [comment]
It's done. 0e8a4eaea062b81c6f6ddf5f4743121d5bc6b2ac 
Give it a go, let me know if there's any issue. :)

**Comment by jackgu1988** [comment]
Yes it works perfectly. Thanks a lot.

What is probably best for new users who won't read through the manual is to backup your old config and then restore it when you disconnect.

**Comment by jotyGill** [comment]
That's good. cheers.
Backing up is easy, restoring after (Ctr + C) is bit tricky. 
Could you open an another issue (suggesting what u said here) so I can close this one?
