### ISSUE TITLE
Allow custom ports

### ISSUE THREAD

**Issue by foopex** [jotyGill/openpyn-nordvpn#38]
In the experimental firewall feature, Is there a way to allow ports, for say, SSH and a Deluge daemon from the local network?

**Comment by jotyGill** [comment]
To clarify, you want to use the openpyn running PC as a SSH and Deluge **server** right? (at present you should be able to use these services on a **local network**, as a **client**)
Yes, I can added an option to specify the ports you want to allow through the firewall.

**Comment by foopex** [comment]
Pretty much.  Specifically, it is linux in a virtual machine on my windows pc, and i connect to it via ssh and deluge client, and I also plan to use it as a proxy for anything I want to force through vpn.  Openpyn seems absolutely perfect for this.  An option to specify ports would be fantastic.

**Comment by jotyGill** [comment]
It seems to working alright, I did't get to do much testing. If anything breaks let me know. Cheers

**Comment by foopex** [comment]
Thanks!!!

**Comment by jotyGill** [comment]
If you like it, don't forget to star, so others can easily find it. Cheers
