### ISSUE TITLE
Problem getting it running on raspberry Pi

### ISSUE THREAD

**Issue by Willverine** [jotyGill/openpyn-nordvpn#49]
Looks like installing and running on raspberry pi doesn't work, using python 3.6.1. 
Installed it as listed in the readme and problem appears like:

## Errors:
1. openpyn -s au10
returns ` Unrecognized option or missing parameter(s) in [CMD-LINE]:1: management-up-down (2.2.1)
Use --help for more information.`

Soon later spits a traceback ending with 
`ModuleNotFoundError: No module named 'gi'`
with reference to the file `.../openpyn/management/management.py line 3 'import gi'`

## Fixed attempts:
I attempted to install packages like `sudo pip3 install gi` which worked and returned the same `unrecognized option` error but had a different traceback ending with 
`SyntaxError: Missing parentheses in call to 'print'`
Which appears to look like python 2 syntax?

## additional info: 
raspberry pi original, so is sorta old and shit. 

1. python -V: `Python 3.6.1`
2. openvpn --version: `OpenVPN 2.2.1 arm-linuxgnueabihf`

any other details necessary guys?

**Comment by jotyGill** [comment]
You probably need python-gobject (apt install python-gobject). Which OS is this? did you install python 6 manually on it or it comes with it?

**Comment by Willverine** [comment]
python-gobject is already installed. 
It is running an older debian wheezy (v7) which is old, but i don't imagine it would be a big deal. 
And yes it definitely didn't come with python 3.6 and i probably installed it manually a year or so back (perhaps). 
After digging around a bit more (and as you may suspect) it appears its probably a python configuration problem and not related to openpyn.

**Comment by jotyGill** [comment]
I see. Yeah I tested things with Jessie not wheezy. About the "management-up-down" option, looks like the version you are using didn't have this option.
I might just get rid of these requirements in the python3.4 branch

**Comment by jotyGill** [comment]
Give this a go. Lets see.

**Comment by Willverine** [comment]
Okay sick i'll give it a shot

**Comment by Willverine** [comment]
now it can't import name 'management' from line 8 of the openpyn.py? 
Maybe my packages are all screwed up

**Comment by jotyGill** [comment]
opps my bad, I needed to remove that.

**Comment by Willverine** [comment]
Well i commented that line out and installed it again (this time successfully) and now it appears to be working!
