### ISSUE TITLE
Add option to get new list after exhausting current server list

### ISSUE THREAD

**Issue by cdloh** [jotyGill/openpyn-nordvpn#51]
Currently if you start the script it collects a list of 3 best servers and then loops through them if they fail.

On the third failure it'd be great if it could go and collect a new best list and try those.

To stop loops if all 3 of those fail it would then exit.

**Comment by jotyGill** [comment]
You can increase this with options -t and -T. If you run it with "openpyn -t 10 -T 10" it will ping top 10 servers, drop the ones that don't respond, sort them by ping average. Then try to connect to the rest of them.

Looking back at this I will probably just merge the -t -T into one option.

**Comment by jotyGill** [comment]
Some how this issue got left out. It's all done now.
