### ISSUE TITLE
Porting on AUR for Arch based system.

### ISSUE THREAD

**Issue by ghost** [jotyGill/openpyn-nordvpn#58]
Please port package on AUR : [https://wiki.archlinux.org/index.php/Arch_User_Repository](url)

**Comment by jotyGill** [comment]
I am looking into it but I don't have ArchLinux setup for testing at the moment. so I'll see

**Comment by Ubermensch85** [comment]
I have created a PKGBUILD (Beta)

`# Maintainer: Ubermensch <francescomarra@protonmail.com>>

pkgname=openpyn-nordvpn-git
_pkgname=openvpn-nordvpn
pkgver=1
pkgrel=1
pkgdesc="Easily connect to and switch between, OpenVPN servers hosted by NordVPN. (+patch leakes)"
arch=('i686' 'x86_64' 'armv6h' 'armv7h')
url="https://github.com/jotyGill/openpyn-nordvpn"
license=('GPL')
depends=('openvpn' 'python-gobject' 'unzip' 'wget')
makedepends=('python' 'git')
provides=('openvpn-nordvpn')
conflicts=('openvpn-nordvpn')
source=('openpyn-nordvpn::git+https://github.com/jotyGill/openpyn-nordvpn.git')
md5sums=('SKIP')
package() {
  cd "$srcdir/openpyn-nordvpn"
  python3 setup.py install --root="${pkgdir}"
}
`
After the tests i put it on AUR and the arch linux users can install  with a simple one "yaourt -S openpyn-nordvpn-git".
Bye

**Comment by jotyGill** [comment]
Good Job!

**Comment by jotyGill** [comment]
I would like to give you credit for that. if you could fetch the latest data from the 'test' branch into your fork and add install option for Arch, I would merge it back.

3. To install on Arch Linux (Maintainer: Ubermensch <francescomarra@protonmail.com>) :
``` bash
sudo yaourt -S openpyn-nordvpn-git
```

**Comment by Ubermensch85** [comment]
I can do a pkgbuild for the test branch give me the link

Sent from ProtonMail Mobile

Attivato dom, dic 3, 2017 alle 13:28, jotyGill <notifications@github.com> ha scritto:

**Comment by jotyGill** [comment]
It's probably good to keep the 'master' branch in the pkgbuild. That's where I keep the stable versions. I push all the little changes I am trying out in the 'test' branch then merge them into 'master'. What I meant was, If you fetch my 'test' branch into your test branch then add the installation on arch instructions in the README.md. I can pull it back in my 'test' branch.

**Comment by Ubermensch85** [comment]
For the test branch the PKGBUILD (openpyn-nordvpn-svn)

`# Maintainer: Ubermensch <francescomarra@protonmail.com>

pkgname=openpyn-nordvpn-svn
pkgver=1.7.3
pkgrel=1
pkgdesc="Easily connect to and switch between, OpenVPN servers hosted by NordVPN. (+patch leakes)"
arch=('x86_64')
url="https://github.com/jotyGill/openpyn-nordvpn"
license=('GPL')
depends=('openvpn' 'python-gobject' 'unzip' 'wget')
makedepends=('python' 'git')
provides=('openvpn-nordvpn')
conflicts=('openvpn-nordvpn')
source=('openpyn-nordvpn::git+https://github.com/jotyGill/openpyn-nordvpn.git#branch=test')
md5sums=('SKIP')


pkgver() {
  cd openpyn-nordvpn
  git describe --long --tags | sed 's/\([^-]*-g\)/r\1/;s/-/./g'
}

package() {
  cd "$srcdir/openpyn-nordvpn"
  python3 setup.py install --root="${pkgdir}"
}
`

For the master branch the PKGBUILD (openpyn-nordvpn-git) 

`# Maintainer: Ubermensch <francescomarra@protonmail.com>

pkgname=openpyn-nordvpn-svn
pkgver=1.7.3
pkgrel=1
pkgdesc="Easily connect to and switch between, OpenVPN servers hosted by NordVPN. (+patch leakes)"
arch=('x86_64')
url="https://github.com/jotyGill/openpyn-nordvpn"
license=('GPL')
depends=('openvpn' 'python-gobject' 'unzip' 'wget')
makedepends=('python' 'git')
provides=('openvpn-nordvpn')
conflicts=('openvpn-nordvpn')
source=('openpyn-nordvpn::git+https://github.com/jotyGill/openpyn-nordvpn.git')
md5sums=('SKIP')


pkgver() {
  cd openpyn-nordvpn
  git describe --long --tags | sed 's/\([^-]*-g\)/r\1/;s/-/./g'
}

package() {
  cd "$srcdir/openpyn-nordvpn"
  python3 setup.py install --root="${pkgdir}"
}
`

**Comment by traxo-xx** [comment]
Two small notes:
1. @jotyGill  Please remove the "sudo" from the yaourt-command. yaourt uses makepg which enforces non-root execution and will exit with an error.
2. @Ubermensch85 While it's up to you how you call your packages, putting the "-svn" suffix on a git-package isn't really correct and might confuse people.
https://wiki.archlinux.org/index.php/VCS_package_guidelines

**Comment by jotyGill** [comment]
Ahh yes, I haven't used Arch in a while. 
I will look into uploading the package on yaourt repo.

**Comment by navdeepio** [comment]
any progress on this?

**Comment by gavsiu** [comment]
`sudo openpyn --init
Traceback (most recent call last):
  File "/usr/bin/openpyn", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'colorama' distribution was not found and is required by openpyn`

I think you need to add "python-colorama" and "wget" to the dependencies list.

**Comment by brenix** [comment]
Sorry to bump this issue, but I came across this post and wanted to share that I have uploaded an AUR package not long ago so that I could use it myself. Figured if anyone was still interested that you can find it below..

AUR Link: [https://aur.archlinux.org/packages/openpyn-nordvpn/](https://aur.archlinux.org/packages/openpyn-nordvpn/)
