### ISSUE TITLE
Dead connections not failing and reconnecting

### ISSUE THREAD

**Issue by foopex** [jotyGill/openpyn-nordvpn#59]
It does not appear that my stalled connections ever fail and reconnect.  I do not see any logs for openvpn or openpyn in /var/log to paste.

**Comment by jotyGill** [comment]
Auto reconnect only works without -d --daemon mode. ATM no logs are being saved. When using it without "-d" you see the output in terminal and info about if connection failed and reconnected. I would eventually make it work in daemon mode but that requires learning async stuff.

**Comment by foopex** [comment]
Oh I see.  Thank you.

Would running openpyn in a screen session without daemon mode work out better?

**Comment by Ubermensch85** [comment]
Yes now works without sudo...

**Comment by jotyGill** [comment]
@foopex  Yeah, it will auto fail over to next server.

@Ubermensch85   different thread mate but it's all good.

**Comment by foopex** [comment]
Ok thanks closing.

**Comment by foopex** [comment]
FYI, after getting this tip, this script has been running with 100% uptime in a virtual machine.  It works so well I forgot it was even there.  I came to look and see if anything has changed, and now it is even better with a system service.   Absolutely fantastic.

**Comment by orangecoloured** [comment]
I'm facing this issue at least twice a day. The connection is stalled and nothing happens.
And I have to manually restart the session.

**Comment by jotyGill** [comment]
This has to do with the way the servers at NordVPN are configured, Process of declaring a connection is dead takes long time and is not perfect. I tried putting the options of faster pings to the server to check connectivity and I think also to not retry (as openpyn handles that by trying the next server instead) but the client side config is ignored and the server side config is used. So until the connection is declared dead I can't do much. I'll look into finding ways of checking the connection myself.
