### ISSUE TITLE
Pings Fail - Invalid Option

### ISSUE THREAD

**Issue by dsanduril** [jotyGill/openpyn-nordvpn#61]
Running on latest OSMC installed on PI 3. Debian Jessie (8.9).

When running openpyn using the defaults ("openpyn nz" for instance) all pings fail. Failure message:

> Ping Failed to : nz7 Skipping it
> ping: invalid option -- 'i'
> BusyBox v1.22.1 (Debian 1:1.22.0-9+deb8u1) multi-call binary.
> 
> Usage: ping [OPTIONS] HOST
> 
> Send ICMP ECHO_REQUEST packets to network hosts
> 
>         -4,-6           Force IP or IPv6 name resolution
>         -c CNT          Send only CNT pings
>         -s SIZE         Send SIZE data bytes in packets (default:56)
>         -t TTL          Set TTL
>         -I IFACE/IP     Use interface or IP address as source
>         -W SEC          Seconds to wait for the first response (default:10)
>                         (after all -c CNT packets are sent)
>         -w SEC          Seconds until ping exits (default:infinite)
>                         (can exit earlier with -c CNT)
>         -q              Quiet, only displays output at start
>                         and when finished

and no connection gets made (script fails with "Top 0 Servers..."). Running openpyn with a specified server ("openpyn -s nz8") works just fine, only problem seems to be when using ping to select servers.

Any thoughts? Missing dependencies? Wrong version of something? Or is it simply "i" vs. "I" (in which case I might be able to figure out the edit)?

**Comment by dsanduril** [comment]
Sort of answered the question, the problem is the BusyBox lite implementation of "ping" which does not accept the interval argument, and also does not return the "mdev" part of the search string. Working on sorting that out, or can try installing the full iputils-ping.

> try:
            ping_proc = subprocess.Popen(
                ["ping", i[0] + ".nordvpn.com", "-i", ".2", "-c", pings],
                stdout=subprocess.PIPE)
            # pipe the output of ping to grep.
            ping_output = subprocess.check_output(
                ("grep", "min/avg/max/mdev"), stdin=ping_proc.stdout)

**Comment by jotyGill** [comment]
I see, yes installing iputils should fix that.
