### ISSUE TITLE
Initialise daemon on boot

### ISSUE THREAD

**Issue by mikesumbler** [jotyGill/openpyn-nordvpn#62]
Hi sorry to be stupid - how best would you recommend getting openpyn to run and start openvpn as a daemon. I have tried init.d script and crontab, neither work. 
Thanks in advance.
Mike

**Comment by jotyGill** [comment]
No question is stupid, scratch that not true lol, but yours isn't. Up until now I haven't done anything to make it persistent through out boots. I am now making it work with systemd. With systemd we should be able to start/stop it, auto run at boot and check vpn status.

**Comment by mikesumbler** [comment]
Wow, the opensource world just amazes me sometimes. I will keenly await the update, great work. 
Sorry to ask - did u have a release date in mind. 

Many thanks mike.

----- Reply message -----

**Comment by jotyGill** [comment]
well for you mates, release date is today. 
before the official release, I'll try and see if anything is broken. (You guys can help me out and test different config variations and OS's if you like). 
Now during the --init it installs itself as a systemd service as well. And we get the benefit of dynamically changing that config file if you run openpyn with -d switch. 
so if you feel like you want to change the country and some options in your openpyn.service you run.
'sudo openpyn au -p 5 -d'     it will update it, reload systemd, (now also start openpyn ).

**Comment by mikesumbler** [comment]
Just installed - works perfectly. Many thanks Mike
