### ISSUE TITLE
Status and Log file parameters

### ISSUE THREAD

**Issue by johnkareoke** [jotyGill/openpyn-nordvpn#63]
Firstly, glad to have found this repository. It's proven really useful. Thanks.

This is possibly a feature request, or perhaps this exists already and I haven't been able to find it. 

I have, until finding this repository, been starting Openvpn with the --log and --status parameters as I have a webinterface that reads the contents of these files to learn about the status of the current connection for example: 

`sudo openvpn --status "/etc/openvpn/status.log" 10 --config "/etc/openvpn/custom/nordvpn/us543.nordvpn.com.tcp443.ovpn"  --auth-user-pass "/etc/openvpn/custom/nordvpn/nordvpn.auth" --log "/etc/openvpn/log.log"`

1. Are these created somewhere by default that I can access? If so where?
2. If note, Are you able to specify similar status and log file destinations with openpyn? If not I think this would make be a useful feature.

Thanks for the help and mostly, thanks for the contribution of this repository!

**Comment by johnkareoke** [comment]
I've taken a look at the code and can answer this myself:
I think it is clear that this doesn't exist so I think it might proved a useful feature request. 

For my purposes I've gone ahead and edited openpyn.py and hardcoded what I need by manually adding `--status /etc/openvpn/status.log  --log /etc/openvpn/log.log"` where appropriate (line 598, 612, 639 and 647).

It might be interesting for others to make this more dynamic and add it command line options, possibly just a generic string that you want to add to the openvpn call.

**Comment by jotyGill** [comment]
Thanks for kind words John. Yes I have thought about adding an option to pass arguments to the openvpn call. It's just the need for it didn't arise. I'll do that at some point (am very busy in the upcoming days.)
Cheers.

**Comment by jotyGill** [comment]
It's all done.
