### ISSUE TITLE
-T switch from usage examples seems to be gone

### ISSUE THREAD

**Issue by o-l-a-v** [jotyGill/openpyn-nordvpn#65]
I tried one of the examples provided, openpyn us -t 10 -T 2 --dedicated
Where the -T 2 switch gave an error. Are there still similar functionality in the script/ program, and if, what options to use?

![t-switch](https://user-images.githubusercontent.com/6450056/32914822-304591fa-cb17-11e7-93d1-2c3110eb425e.PNG)

**Comment by jotyGill** [comment]
-t -T have been merged into -t. if any ping fails to a server, that server would be excluded from the list. so just simply use -t 10 that will do.
