### ISSUE TITLE
Installation Method for MacOS

### ISSUE THREAD

**Issue by 1951FDG** [jotyGill/openpyn-nordvpn#71]
Hi,

First of all thanks for creating this, it's really useful. I've managed to get it working on MacOS, and I wanted to give feedback. See installation method below, and comments regarding some minor code changes.

`/usr/share` is protected by System Integrity Protection on MacOS

If System Integrity Protection is on, the below commands will not work, meaning that every time a Mac user would want to download/update vpn config files, they would also need to disable it before and reenable it after
```
sudo openpyn --init
sudo openpyn --update
```
To enable or disable System Integrity Protection, you must boot to Recovery OS by restarting your machine and holding down the Command and R keys at startup and run the csrutil command from the Terminal. After enabling or disabling System Integrity Protection on a machine, a reboot is required.

**Installation Methods**

1. For MacOS

```
Boot to Recovery OS.
Launch Terminal from the Utilities menu.
csrutil disable
shutdown -r now

xcode-select --install
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile
brew install python3
brew install wget
brew install openvpn
sudo brew services start openvpn

git clone https://github.com/jotyGill/openpyn-nordvpn.git
cd openpyn-nordvpn
sudo python3 setup.py install
sudo openpyn --init

Boot to Recovery OS.
Launch Terminal from the Utilities menu.
csrutil enable
shutdown -r now
```

libnotify doesn’t work on MacOS, below commands eliminate a couple of warnings for those that dislike warnings, a workaround would be to prevent MANAGEMENT code from being executed for MacOS users or use a multi-platform notifier…

```
brew install pygobject3 --with-python3
brew install libnotify
```
**Code changes required (which should not have impact for other platforms)**

Below command doesn't work on macOS (Tested: 10.11.6)
```
ping es30.nordvpn.com -i .2 -c 5
```
This command does :)
```
ping -i .2 -c 5 es30.nordvpn.com
```

Ping returns slightly different output on MacOS (Tested: 10.11.6)

`round-trip min/avg/max/stddev = 135.534/140.502/148.232/4.704 ms`

Notice **min/avg/max/stddev** instead of **min/avg/max/mdev**

In **openpyn.py**, could you make these changes:

> ["ping", i[0] + ".nordvpn.com", "-i", ".2", "-c", pings] > **["ping", "-i", ".2", "-c", pings, i[0] + ".nordvpn.com"]**

> ("grep", "min/avg/max/mdev"), stdin=ping_proc.stdout) > **("grep", "min/avg/max/”), stdin=ping_proc.stdout)**

Forking and opening a pull request for these minor changes would be overkill, hopefully you won't mind testing and making these changes

**Comment by jotyGill** [comment]
Hi there, thank you for your contribution. I didn't think It would work this easily on mac. I can push these changes through. I have made some changes to the code in the "test" branch which I am about to push to master. Mainly systemd integration. If we want to support MacOS we would need to skip the systemd integration if the detected OS is Mac. I would highly appreciate your help in doing that.

**Comment by jotyGill** [comment]
I have tried to make version 2 compatible with MacOS. Now there shouldn't be a need to install pygobject3 or libnotify. Could you please give it a try, I don't have a mac to test it. Thanks :)

**Comment by 1951FDG** [comment]
Hi, I will test it this week! Thanks. I may be able to help out with "skipping" the systemd integration for MacOS as well. It would also be great to port this to asus merlin dd-wrt, it would be quite the challenge, if anyone is up for it and wants to collaborate, let me know.

**Comment by jotyGill** [comment]
Hi, well systemd stuff should be skipped as well, I put in a check to only install systemd service file if it's a linux. If I am not missing anything it should work.

**Comment by 1951FDG** [comment]
Did some testing and the code requires some changes:

`detected_os == sys.platform` should be `detected_os = sys.platform`

Otherwise, I get error `UnboundLocalError: local variable 'detected_os' referenced before assignment`

Also noticed,` resolvconf_exists is False`, this is not the same as `resolvconf_exists = False`, right? As in testing vs setting a variable? Are you testing me :)

"Fixed" code
```
if sys.platform == "linux":
        detected_os = platform.linux_distribution()[0]
        resolvconf_exists = os.path.isfile("/sbin/resolvconf")
        #resolvconf_exists = False
    else:
        detected_os = sys.platform
        resolvconf_exists = False
```

"Optimized" code
```
detected_os = sys.platform
    if detected_os == "linux":
        detected_os = platform.linux_distribution()[0]
        resolvconf_exists = os.path.isfile("/sbin/resolvconf")
        #resolvconf_exists = False
    else:
        resolvconf_exists = False
```

Otherwise it works fine, still get some openpyn-management warnings, but those I can fix some time later, as they are harmless, probably requires some checks like the above as well.

**Comment by 1951FDG** [comment]
Also, here are update instructions for users on MacOS

To be able to run new modified code, using `sudo python3 setup.py install` and avoid the System Integrity Protection, remove from `setup.py`:

```
 data_files=[('/usr/share/openpyn', ['./openpyn/scripts/manual-dns-patch.sh', './openpyn/scripts/update-resolv-conf.sh', './openpyn/config.json'])],
```

Is there another way to prevent `setup.py` from processing the data_files part?

Also, uninstall instructions for MacOS (should work on other platforms as well)

I did `sudo python3 setup.py install --record openpyn-nordvpn.txt` and did manual scanning of files as well

**Step 1**
```
sudo pip3 uninstall openpyn
```
This deletes _/usr/local/lib/python3.6/site-packages/openpyn-1.7.3-py3.6.egg_

**Step 2**
```
rm -rf /usr/local/bin/openpyn
rm -rf /usr/local/bin/openpyn-management
rm -rf /usr/share/openpyn
```
This deletes remaining files

```
rm -rf /usr/local/bin/chardetect
```
This one is optional as it may be installed by other modules as well !/?

**Comment by jotyGill** [comment]
I am going to pretend that I was testing you. It totally wasn't me being careless and just typing words and expecting magic. haha
To get arround System Integrity Protection on MacOS, lets see if this setup file works. 5c5cfaefed249e50886a43f4c964ff263af52761

**Comment by 1951FDG** [comment]
That setup file works, but I wouldn't push it to the master branch, because ./openpyn/scripts/manual-dns-patch.sh and  ./openpyn/config.json are still being used.

I also got my dev setup working, here is my 1st pull request, https://github.com/jotyGill/openpyn-nordvpn/pull/78
