### ISSUE TITLE
NordVPN is blocked by ISP

### ISSUE THREAD

**Issue by mrahmadt** [jotyGill/openpyn-nordvpn#79]
Hello

NordVPN is blocked by my ISP so the command
`openpyn --init`
will not work because it's trying to download
https://nordvpn.com/api/files/zip

I suggest if you change the link to https://downloads.nordcdn.com/configs/archives/servers/ovpn.zip

**Comment by jotyGill** [comment]
Hello there,
I see, well, using the this new link would required some changes as the structure and names of the files in this zip are different. If this happens to others as well I will change the code to work with this new link. 
For you I just created a little script to rename the files.
You can skip the "--init" bit by doing the following.

1: Store Credentials,

`sudo touch /usr/share/openpyn/credentials`
`sudo echo "username" > /usr/share/openpyn/credentials`
`sudo echo "password" >> /usr/share/openpyn/credentials`
`sudo chmod 600 /usr/share/openpyn/credentials`

2: Setup opvn files.
download and extract https://downloads.nordcdn.com/configs/archives/servers/ovpn.zip  

`sudo mkdir /usr/share/openpyn/files`

3: copy all ovpn files (both tcp and udp folders) into /usr/share/openpyn/files

4: copy this python script into /usr/share/openpyn/files. and run it.
`sudo python3 rename.py`

That's it, should work.

**Comment by mrahmadt** [comment]
Thanks for the instruction, I will use it

This is the official link from NordVPN to download the OVPN

https://nordvpn.com/tutorials/linux/openvpn/

**Comment by Steve0t** [comment]
Hey, 

First, thanks fur putting this together, looks great

I got the same issue, I tried your script but the file names have changed from that link. I would greatly appreciate if you can make the change to allow the https://downloads.nordcdn.com/configs/archives/servers/ovpn.zip  link to work.

**Comment by jotyGill** [comment]
The commit is not pushed to the master branch yet. Grab the 'test' branch. Try it out.

`sudo pip3 uninstall openpyn`
`git clone --branch test https://github.com/jotyGill/openpyn-nordvpn.git`
`cd openpyn-nordvpn`
`sudo python3 setup.py install`
