### ISSUE TITLE
Run on Python <3.5

### ISSUE THREAD

**Issue by gsdefender** [jotyGill/openpyn-nordvpn#82]
openpyn uses `subprocess.run` to spawn the openvpn process that is available only on Python 3.5 and newer; OS that come without it (e.g. Debian 8.9) bomb out of the execution because they come with less recent Python versions.

As pointed out in [this StackOverflow question](https://stackoverflow.com/questions/40590192/getting-an-error-attributeerror-module-object-has-no-attribute-run-while), backporting the function is easy, so a patch could be devised as follows:

<pre>def backport_run(*popenargs, input=None, check=False, **kwargs):<br/>
    if input is not None:<br/>
        if "stdin" in kwargs:<br/>
            raise ValueError("stdin and input arguments may not both be used.")<br/>
        kwargs["stdin"] = subprocess.PIPE<br/>

    process = subprocess.Popen(*popenargs, **kwargs)
    try:
        stdout, stderr = process.communicate(input)
    except:
        process.kill()
        process.wait()
        raise
    retcode = process.poll()
    if check and retcode:
        raise subprocess.CalledProcessError(
            retcode, process.args, output=stdout, stderr=stderr)
    return retcode, stdout, stderr

try:
        subprocess.run("/bin/ls")
except AttributeError:
        subprocess.run = backport_run
</pre>

This is enough to run openpyn successfully.

**Comment by jotyGill** [comment]
ah python 3.4 support, I have gone twice in that direction. There's an older abandoned branch, also I ported it back in version 1.7.x. some subprocess methods in 3.4 handle output differently, not what I wanted. And even Debian 9 has 3.5 so I didn't bother anymore. 
You can install the 1.7.3 release, it doesn't have systemd service file and some other bells but It will work.

**Comment by gsdefender** [comment]
I have been testing the code snippet I have posted in my previous message on Debian 8.10 and it works OK so far
