### ISSUE TITLE
Include switch for netflix

### ISSUE THREAD

**Issue by mnt-grrrl** [jotyGill/openpyn-nordvpn#84]
Nord publishes a list of servers optimized for netflix. It would be great if there was a netflix option. I do not know if this information is published by the api but it seems like it should.

Thanks in Advance
MG

**Comment by jotyGill** [comment]
Hi, there's no info about servers being optimized for netflix in the api. I found this (https://support.nordvpn.com/#/General-Info/1047407532/How-to-securely-watch-Netflix-with-NordVPN.htm) where they mention the servers. I am working on creating a --netflix option.

**Comment by celevra** [comment]
this is the official download link for the configs for the obfuscated (thats the right term) servers
http://downloads.nordcdn.com/configs/archives/servers/ovpn_xor.zip

**Comment by celevra** [comment]
duplicate to #67
