### ISSUE TITLE
slow pings/best servers require high -t

### ISSUE THREAD

**Issue by mnt-grrrl** [jotyGill/openpyn-nordvpn#85]
So I live in the US and started the software with -t 10 and got all servers with 200ms+ ping times. I increased to -t 45 (which was probably over killed) and got same servers with 50-100ms ping time. The thing is the pinging process is slow. So I wondered about using netselect to speed up the process? Or figure out a way to get low ping servers with -t 5-10? Thoughts?

**Comment by jotyGill** [comment]
Yeah, I felt that the pings are slow as well, making the -t large would slow things down. First I thought It could be how they are being handled in openpyn, I use subprocess.Popen to ping then pipe then subprocess.check_output(("grep"...
I tested different approach that's not it. Takes same amount,
Then I thought It could be DNS requests taking time, Wireshark says they are pretty quick.
The packet capture showed, reverse dns lookups, according to the man page of ping "-n" omits them.

So Yeah, just by inserting "-n", **pings are now x8 times faster :)**

Pinging 30 servers initially took 202 seconds now it takes 26.

Before
`python3 test.py  0.15s user 0.15s system 0% cpu 3:22.90 total`
After
`python3 test.py  0.14s user 0.14s system 1% cpu 25.997 total`
