### ISSUE TITLE
openpyn: error: unrecognized arguments: -T 2

### ISSUE THREAD

**Issue by fossil** [jotyGill/openpyn-nordvpn#87]
xxx@xxx:~/$ openpyn nl -t 10 -T 2 --p2p
usage: openpyn [-h] [-v] [--init] [-s SERVER] [--tcp] [-c COUNTRY_CODE]
               [-a AREA] [-d] [-m MAX_LOAD] [-t TOP_SERVERS] [-p PINGS] [-k]
               [-x] [--update] [--skip-dns-patch] [-f]
               [--allow INTERNALLY_ALLOWED [INTERNALLY_ALLOWED ...]]
               [-l [LIST_SERVERS]] [--silent] [--p2p] [--dedicated] [--tor]
               [--double] [--anti-ddos] [--test]
               [country]
openpyn: error: unrecognized arguments: -T 2

**Comment by jotyGill** [comment]
-T and -t were merged into -t 
you can use:

`openpyn nl -t 10 --p2p`

**Comment by fossil** [comment]
Then you need to update the guide.

15 янв. 2018 г. 1:07 ДП пользователь "jotyGill" <notifications@github.com>
написал:

**Comment by brubrant** [comment]
Because I'm paying a lot you so you should keep the guide updated, lazy

Em 19 de jan de 2018 22:45, "fossil" <notifications@github.com> escreveu:

**Comment by jotyGill** [comment]
Oh no, I am going to get a paycut because of this?

**Comment by fossil** [comment]
it is up to you.
I thought you are interested in delivery good quality and the feedback.

2018-01-22 13:31 GMT+01:00 jotyGill <notifications@github.com>:
