### ISSUE TITLE
running post script

### ISSUE THREAD

**Issue by celevra** [jotyGill/openpyn-nordvpn#89]
hi,

after the connect i want to run a script that enables ip_forwarding and masquerading, would be nice if openpyn could run that script automaticly for me

regards

celevra

**Comment by jotyGill** [comment]
I have added the ability to pass through any openvpn options. ba6b6efd853212ec7ac927a067918a62da4d616a d4a4f9e62b26c133446be0f644ef6522a5c7d737
If you are using a non Debian based os you could simply use. 
`openpyn uk -o '--script-security 2 --up \etc\script.sh'`
For Diebian based OSs --up is already utilized either you try something else or you could just merge your script with "openpyn/scripts/update-resolv-conf.sh"
Cheers

**Comment by celevra** [comment]
Perfect, thank you for your work
