### ISSUE TITLE
Support other VPN providers

### ISSUE THREAD

**Issue by mrahmadt** [jotyGill/openpyn-nordvpn#91]
Hello

I really liked the functionality provided by openpyn-nordvpn, such as selecting the best VPN server and auto restart.

I'm currently building a VPN gateway VM (will share the project later after creating the github rep.).

So my question, any plan to convert this project into a VPN platform that supports other VPN providers?

Thanks

**Comment by jotyGill** [comment]
Support for other providers would require quite a bit of work. I'll look into it and see what providers are being requested. IPVanish has been mentioned a couple of times.

Cheers
